const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const core=require('../web/reorder-core.js');
const menu=[{id:'soups',name:'Soups',items:[{id:'soup',name:'Soup',price:'£4.00',in_stock:true}]},{id:'chinese',name:'Chinese',items:[{id:'chicken',name:'Chicken',price:'£8.00',in_stock:true}]}];
const groups=new Map([['soup',[{id:'roll',name:'Choose your roll',type:'single',required:true,min:1,max:1,options:[{id:'soft',name:'Soft roll',price:0},{id:'crispy',name:'Crispy roll',price:.5}]}]],['chicken',[{id:'side',name:'Choose your side',type:'single',required:true,min:1,max:1,options:[{id:'chips',name:'Chips',price:0},{id:'rice',name:'Boiled rice',price:0}]},{id:'remove',name:'Remove ingredients',type:'multiple',min:0,max:4,options:[{id:'onion',name:'No onion',price:0}]}]]]);
const saved=[{id:'soup',price:'£3.50',qty:2,modifiers:['Choose your roll: Crispy roll'],modifier_total:0},{id:'chicken',price:'£8.00',qty:1,modifiers:['Choose your side: Chips'],removed:['onion']}];
let lines=core.restore(saved,menu,groups);assert.equal(lines.length,3);assert.equal(lines[0].price,'£4.00');assert.equal(lines[0].modifierTotal,.5);assert.match(lines[0].reorderNote,/Price/);assert.equal(lines[0].category_name,'Soups');assert.equal(lines[2].modifiers[1].option_ids[0],'onion');assert.equal(lines[2].reorderIssue,'');
assert.match(core.restore([{id:'soup',qty:1,price:'£4',modifiers:[]}],menu,groups)[0].reorderIssue,/roll/);
assert.match(core.restore([{id:'missing',qty:1}],menu,groups)[0].reorderIssue,/unavailable/);
assert.equal(core.namesToIds('A, B',[{id:'one',name:'A, B'},{id:'a',name:'A'},{id:'b',name:'B'}]),null);
assert.equal(core.namesToIds('Same',[{id:'a',name:'Same'},{id:'b',name:'Same'}]),null);
assert.throws(()=>core.restore([{id:'soup',qty:41}],menu,groups));
assert.match(core.restore([{id:'soup',qty:1,price:'£4',modifiers:['Old option: Gone']}],menu,groups)[0].reorderIssue,/Old option/);
const clone=x=>JSON.parse(JSON.stringify(x));
function harness(items=saved){
 const elements=new Map(),storage=new Map(),calls=[];let authChange;const timers=[];
 const element=id=>{if(!elements.has(id))elements.set(id,{id,value:id==='customerName'?'Sample':id==='customerPhone'?'01410000000':'',innerHTML:'',textContent:'',disabled:false,dataset:{},classList:{add(){},remove(){},contains(){return false},toggle(){}},querySelectorAll:()=>[],append(){},before(){},scrollIntoView(){}});return elements.get(id)};
 const c={console,Map,Set,URL,URLSearchParams,JSON,String,Number,Math,Date,Error,document:{getElementById:element,createElement:()=>element('new')},window:{DexterReorder:core},sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},location:{href:'https://fixture.invalid/collection-order-test.html?reorder=order-a',search:'?reorder=order-a'},history:{replaceState(_a,_b,url){c.location.search='';calls.push({action:'replace',url})}},setTimeout:fn=>timers.push(fn),categories:clone(menu),cart:{},U:'https://fixture.invalid',K:'synthetic-public',esc:s=>String(s),renderMenu(){},loadMenu:async()=>{},loadOrders(){},api:async body=>{calls.push(body);return {orders:[{id:'order-a',items:clone(items)}]}}};
 c.user={user:{id:'sample-a'},access_token:'synthetic-only'};c.sb={auth:{getSession:async()=>({data:{session:c.user}}),onAuthStateChange:fn=>{authChange=fn}}};
 c.failModifiers=false;c.creates=0;c.fetch=async(url,options)=>{if(url.includes('loyalty_modifier_public')){if(c.failModifiers)return {ok:false};const offset=Number(new URL(url).searchParams.get('offset'));const rows=[];for(const [id,gs]of groups)for(const g of gs)for(const o of g.options)rows.push({menu_item_id:id,group_id:g.id,group_name:g.name,selection_type:g.type,required:g.required,min_select:g.min,max_select:g.max,option_id:o.id,option_name:o.name,price_delta:o.price});return {ok:true,json:async()=>offset?[]:rows}}if(url.includes('loyalty_menu_public')&&c.failMenu)return {ok:false};if(url.includes('loyalty_menu_public'))return {ok:true,json:async()=>clone(c.categories)};const body=JSON.parse(options.body);assert.equal(body.action,'create');c.creates++;calls.push(body);if(c.createDelay)await c.createDelay;return {ok:true,json:async()=>({order:{order_number:'DEMO'}})}};
 vm.createContext(c);const src=fs.readFileSync(require.resolve('../web/collection-modifiers-live.js'),'utf8').replace(/\}\)\(\);\s*$/, 'window.test={state,init,placeModified,openCustom,addCurrent,importReorder,loadModifierData};})();');vm.runInContext(src,c);return {c,t:c.window.test,element,calls,storage,change(user){c.user=user;authChange('SIGNED_IN',user)}};
}
(async()=>{
 let h=harness();await h.t.init();assert.equal(h.t.state.lines.length,3);assert.equal(h.c.creates,0);await h.t.importReorder();assert.equal(h.t.state.lines.length,3);await h.t.placeModified();assert.equal(h.c.creates,1);assert.equal(h.calls.find(c=>c.action==='create').items.length,3);
 h=harness([{id:'soup',price:'£4',qty:1,modifiers:[]}]);await h.t.init();await h.t.placeModified();assert.equal(h.c.creates,0);h.t.openCustom('soup',0);h.t.state.selected.set('roll',new Set(['soft']));h.t.addCurrent();assert.equal(h.t.state.lines.length,1);await h.t.placeModified();assert.equal(h.c.creates,1);
 h=harness();await h.t.init();h.c.categories[0].items[0].in_stock=false;await h.t.placeModified();assert.equal(h.c.creates,0);assert.match(h.element('msg').textContent,/unavailable/);
 h=harness();await h.t.init();h.c.categories[0].items[0].price='£5.00';await h.t.placeModified();assert.equal(h.c.creates,0);assert.match(h.element('msg').textContent,/Prices changed/);await h.t.placeModified();assert.equal(h.c.creates,1);
 h=harness();await h.t.init();let resolve;h.c.createDelay=new Promise(r=>resolve=r);const first=h.t.placeModified();await new Promise(r=>setImmediate(r));await h.t.placeModified();assert.equal(h.c.creates,1);resolve();await first;
 h=harness();await h.t.init();h.change({user:{id:'sample-b'},access_token:'synthetic-b'});assert.equal(h.t.state.lines.length,0);h.change({user:{id:'sample-a'},access_token:'synthetic-a'});assert.equal(h.t.state.lines.length,3);h.change(null);assert.equal(h.t.state.lines.length,0);await h.t.placeModified();assert.equal(h.c.creates,0);
 h=harness();await h.t.init();h.c.failMenu=true;await h.t.placeModified();assert.equal(h.c.creates,0);assert.match(h.element('msg').textContent,/current menu/);
 h=harness();await h.t.init();let finish;h.c.createDelay=new Promise(r=>finish=r);const pending=h.t.placeModified();await new Promise(r=>setImmediate(r));h.change({user:{id:'sample-b'},access_token:'synthetic-b'});finish();await pending;assert.equal(h.t.state.lines.length,0);assert(!h.element('msg').innerHTML.includes('sent to the kitchen'));
 h=harness();h.c.failModifiers=true;await h.t.init();assert.equal(h.t.state.lines.length,0);h.c.failModifiers=false;await h.t.loadModifierData();await h.t.importReorder();assert.equal(h.t.state.lines.length,3);
 console.log('PASS: quantities, category, roll/side/removals, current prices, ambiguity, unavailable items, manual correction, repeat import, checkout, price reconfirmation, duplicate clicks, account baskets, modifier retry. No network or kitchen calls.');
})().catch(e=>{console.error(e);process.exitCode=1});
