const assert=require('node:assert/strict'),C=require('../sunday/core.js');
const now=new Date('2026-09-02T12:00:00Z');
const state=()=>({config:{enabled:true,date:'2026-09-06',slots:['12:00','12:15'],stock:{chicken:30,beef:20},override:'auto'},orders:[]});
const draft=()=>({...C.empty(),meals:{chicken:1,beef:0},name:'Test Customer',phone:'07000000000',slot:'12:00'});
for(const meat of ['chicken','beef'])for(const extra of ['chicken','beef']){const s=state(),d=draft();d.meals={chicken:0,beef:0};d.meals[meat]=1;d.extras[extra]=1;const o=C.create(s,d,`request-${meat}-${extra}`,now);assert.equal(o.total_pence,C.meals[meat].price+C.extras[extra].price);assert.equal(o.items[1].name,C.extras[extra].name)}
{const s=state(),d=draft();d.meals.beef=2;for(const k in d.extras)d.extras[k]=2;const o=C.create(s,d,'request-mixed',now);assert.equal(o.total_pence,1095+2*1295+2*(75+100+100+150+250+350));assert.equal(s.config.stock.chicken,29);assert.equal(s.config.stock.beef,18);assert.equal(C.create(s,d,'request-mixed',now).id,o.id);assert.equal(s.orders.length,1);const p=C.prep(s.orders,s.config.date);assert.equal(p.dinners,3);assert.deepEqual(p.slots['12:00'],{chicken:1,beef:2});assert.equal(p.extras.chicken,2);assert.equal(p.extras.beef,2);C.transition(s,o.id,'accept');C.transition(s,o.id,'preparing');C.transition(s,o.id,'ready');C.transition(s,o.id,'collected');assert.equal(o.status,'collected')}
for(const meat of ['chicken','beef']){const s=state(),d=draft();s.config.stock[meat]=0;d.meals={chicken:0,beef:0};d.meals[meat]=1;assert.throws(()=>C.create(s,d,'request-stock',now),/sold out/);d.meals[meat]=0;d.meals[meat==='chicken'?'beef':'chicken']=1;C.create(s,d,'request-other',now)}
{const c=state().config;assert(C.open(c,new Date('2026-09-04T18:59:59Z')));assert(!C.open(c,new Date('2026-09-04T19:00:00Z')));c.override='open';assert(C.open(c,new Date('2026-09-05T12:00:00Z')));c.override='closed';assert(!C.open(c,now));c.override='open';c.enabled=false;assert(!C.open(c,now));c.enabled=true;assert(!C.open(c,new Date('2026-09-07T10:00:00Z')))}
{const c=state().config;c.date='2026-12-06';assert(C.open(c,new Date('2026-12-04T19:59:59Z')));assert(!C.open(c,new Date('2026-12-04T20:00:00Z')))}
{const s=state(),d=draft();d.slot='14:00';assert.throws(()=>C.create(s,d,'request-slot',now),/available/);d.slot='12:00';d.meals.chicken=1.5;assert.throws(()=>C.create(s,d,'request-qty',now),/whole/);d.meals.chicken=0;d.extras.beef=1;assert.throws(()=>C.create(s,d,'request-extra',now),/at least one/)}
{const s=state(),d=draft(),o=C.create(s,d,'request-reject',now);C.transition(s,o.id,'reject','Item unavailable');assert.equal(s.config.stock.chicken,30);assert.equal(C.prep(s.orders,s.config.date).dinners,0);assert.throws(()=>C.transition(s,o.id,'reject','Other'));assert.equal(s.config.stock.chicken,30)}
{const c=state().config;c.date='2026-09-05';assert.throws(()=>C.validateConfig(c),/Sunday/);c.date='2026-09-06';c.slots=['12:00','12:00'];assert.throws(()=>C.validateConfig(c),/unique/)}
console.log('PASS: both meals, mixed meals, all four meat/extra combinations, multiple extras, integer prices, stock, idempotency, UK summer/winter cutoff, reopen/close, slots, prep totals, status lifecycle and rejected-stock release. Offline tests only.');
