const assert=require('node:assert/strict'),C=require('../sunday/core.js');
const now=new Date('2026-09-02T12:00:00Z');
const stock=()=>({chicken:30,beef:20,kids_chicken:20,kids_beef:15});
const state=()=>({config:{enabled:true,date:'2026-09-06',slots:['12:00','12:15'],stock:stock(),override:'auto'},orders:[]});
const draft=()=>({...C.empty(),meals:{...C.empty().meals,chicken:1},name:'Test Customer',phone:'07000000000',slot:'12:00'});
const rid=s=>'request-'+s.replaceAll('_','-');
for(const meal of Object.keys(C.meals)){const s=state(),d=draft();d.meals=Object.fromEntries(Object.keys(C.meals).map(k=>[k,0]));d.meals[meal]=1;const o=C.create(s,d,rid(meal),now);assert.equal(o.total_pence,C.meals[meal].price);assert.equal(o.items[0].name,C.meals[meal].name);assert.equal(s.config.stock[meal],stock()[meal]-1)}
assert.equal(C.meals.kids_chicken.price,695);assert.equal(C.meals.kids_beef.price,795);
for(const meal of Object.keys(C.meals))for(const extra of ['chicken','beef']){const s=state(),d=draft();d.meals=Object.fromEntries(Object.keys(C.meals).map(k=>[k,0]));d.meals[meal]=1;d.extras[extra]=1;const o=C.create(s,d,rid(meal+'-'+extra),now);assert.equal(o.total_pence,C.meals[meal].price+C.extras[extra].price);assert.equal(o.items[1].name,C.extras[extra].name)}
{const s=state(),d=draft();d.meals.beef=2;d.meals.kids_chicken=1;d.meals.kids_beef=1;for(const k in d.extras)d.extras[k]=2;const o=C.create(s,d,'request-mixed',now);assert.equal(o.total_pence,1095+2*1295+695+795+2*(75+100+100+150+250+350));assert.equal(s.config.stock.chicken,29);assert.equal(s.config.stock.beef,18);assert.equal(s.config.stock.kids_chicken,19);assert.equal(s.config.stock.kids_beef,14);assert.equal(C.create(s,d,'request-mixed',now).id,o.id);assert.equal(s.orders.length,1);const p=C.prep(s.orders,s.config.date);assert.equal(p.dinners,5);assert.equal(p.kids_chicken,1);assert.equal(p.kids_beef,1);assert.deepEqual(p.slots['12:00'],{chicken:1,beef:2,kids_chicken:1,kids_beef:1});assert.equal(p.extras.chicken,2);assert.equal(p.extras.beef,2);C.transition(s,o.id,'accept');C.transition(s,o.id,'preparing');C.transition(s,o.id,'ready');C.transition(s,o.id,'collected');assert.equal(o.status,'collected')}
for(const meal of Object.keys(C.meals)){const s=state(),d=draft();s.config.stock[meal]=0;d.meals=Object.fromEntries(Object.keys(C.meals).map(k=>[k,0]));d.meals[meal]=1;assert.throws(()=>C.create(s,d,rid('stock-'+meal),now),/sold out/)}
{const c=state().config;assert(C.open(c,new Date('2026-09-04T18:59:59Z')));assert(!C.open(c,new Date('2026-09-04T19:00:00Z')));c.override='open';assert(C.open(c,new Date('2026-09-05T12:00:00Z')));c.override='closed';assert(!C.open(c,now));c.override='open';c.enabled=false;assert(!C.open(c,now));c.enabled=true;assert(!C.open(c,new Date('2026-09-07T10:00:00Z')))}
{const c=state().config;c.date='2026-12-06';assert(C.open(c,new Date('2026-12-04T19:59:59Z')));assert(!C.open(c,new Date('2026-12-04T20:00:00Z')))}
{const s=state(),d=draft();d.slot='14:00';assert.throws(()=>C.create(s,d,'request-slot',now),/available/);d.slot='12:00';d.meals.chicken=1.5;assert.throws(()=>C.create(s,d,'request-qty',now),/whole/);d.meals.chicken=0;d.extras.beef=1;assert.throws(()=>C.create(s,d,'request-extra',now),/at least one/)}
{const s=state(),d=draft(),o=C.create(s,d,'request-reject',now);C.transition(s,o.id,'reject','Item unavailable');assert.equal(s.config.stock.chicken,30);assert.equal(C.prep(s.orders,s.config.date).dinners,0);assert.throws(()=>C.transition(s,o.id,'reject','Other'));assert.equal(s.config.stock.chicken,30)}
{const c=state().config;c.date='2026-09-05';assert.throws(()=>C.validateConfig(c),/Sunday/);c.date='2026-09-06';c.slots=['12:00','12:00'];assert.throws(()=>C.validateConfig(c),/unique/)}
console.log('PASS: adult and kids chicken/beef meals, mixed meals, separate chicken/beef extras, multiple extras, integer prices, stock, idempotency, UK summer/winter cutoff, reopen/close, slots, prep totals, status lifecycle and rejected-stock release. Offline tests only.');
