plugins { id 'com.android.application' }

android {
    namespace 'co.dexters.loyalty'
    compileSdk 35

    defaultConfig {
        applicationId 'co.dexters.livepos'
        minSdk 26
        targetSdk 35
        versionCode 1014
        versionName '1.014-square'
    }
}

dependencies {
    implementation 'com.squareup.sdk:point-of-sale-sdk:2.0'
}
