plugins { id 'com.android.application' }

android {
    namespace 'co.dexters.terminal'
    compileSdk 35

    defaultConfig {
        applicationId 'co.dexters.terminal'
        minSdk 26
        targetSdk 35
        versionCode Integer.parseInt(System.getenv('DEXTERS_VERSION_CODE') ?: '2')
        versionName System.getenv('DEXTERS_VERSION_NAME') ?: '1.1-dexters'
    }

    buildFeatures {
        aidl = true
    }
}


dependencies {
    implementation 'androidx.core:core:1.13.1'
}
