plugins { id 'com.android.application' }

android {
    namespace 'co.dexters.loyalty'
    compileSdk 35
    buildFeatures { aidl true }

    defaultConfig {
        applicationId 'co.dexters.livepos'
        minSdk 26
        targetSdk 35
        versionCode 1017
        versionName '1.017-square-auto-return'
    }
}

dependencies {
    implementation 'com.squareup.sdk:point-of-sale-sdk:2.0'
}
