import {createClient} from "npm:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const J=(body:any,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"content-type":"application/json","cache-control":"no-store"}});
const mealPrices:any={chicken:1499,beef:1499,mixed:1499,kids_chicken:999,kids_beef:999,kids_mixed:999};
const extraPrices:any={yorkshire:75,gravy:100,stuffing:100,potatoes:150,chicken:250,beef:350};
const clean=(o:any,keys:string[])=>Object.fromEntries(keys.map(k=>[k,Math.max(0,Math.min(50,Number.parseInt(String(o?.[k]??0),10)||0))]));
function normal(o:any){const meals:any={},extras:any={};for(const i of o.items||[])(i.kind==='meals'?meals:extras)[i.key]=Number(i.qty)||0;const paid=Math.max(0,Number(o.total_pence||0)-Number(o.balance_pence||0));return {...o,meals,extras,paid_pence:paid,payment_status:Number(o.balance_pence||0)<=0?'paid_full':paid>0?'deposit_paid':'unpaid'} }
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return J({error:'POST required'},405);const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))return J({error:'Not authenticated'},401);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const uc=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:{user}}=await uc.auth.getUser();if(!user)return J({error:'Invalid session'},401);const db=createClient(url,service);const {data:staff}=await db.from('profiles').select('role').eq('id',user.id).single();if(!staff||!['staff','manager','admin'].includes(String(staff.role)))return J({error:'Staff access required'},403);let b:any={};try{b=await req.json()}catch{return J({error:'Invalid request'},400)};const action=String(b.action||'');try{
 if(action==='customer_search'){const q=String(b.query||'').trim().slice(0,80);if(q.length<2)return J({customers:[]});const digits=q.replace(/\D/g,'');let query=db.from('profiles').select('id,full_name,phone,loyalty_code').eq('role','customer').limit(20);query=digits.length>=3?query.ilike('phone','%'+digits+'%'):query.or('full_name.ilike.%'+q.replace(/[,%]/g,'')+'%,loyalty_code.ilike.%'+q.replace(/[,%]/g,'')+'%');const {data,error}=await query.order('full_name');if(error)throw error;return J({customers:data||[]})}
 if(['list','outstanding','prep_summary'].includes(action)){const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),end=new Date(today+'T12:00:00Z');end.setUTCDate(end.getUTCDate()+7);let q=db.from('sunday_roast_orders').select('*').gte('collection_date',today).lte('collection_date',end.toISOString().slice(0,10)).not('status','in','("collected","rejected","no_show","payment_failed")').order('collection_date').order('collection_slot').order('created_at');if(b.collection_date)q=q.eq('collection_date',String(b.collection_date));if(action==='outstanding')q=q.gt('balance_pence',0);const {data,error}=await q;if(error)throw error;const rows=(data||[]).map(normal);if(action!=='prep_summary')return J({orders:rows});const totals:any={dinners:0,chicken:0,beef:0,mixed:0,kids_chicken:0,kids_beef:0,kids_mixed:0};for(const o of rows)for(const [k,v] of Object.entries(o.meals||{})){totals[k]=(totals[k]||0)+Number(v||0);totals.dinners+=Number(v||0)}return J({orders:rows,totals})}
 if(action==='create'){const cid=String(b.customer_id||'');const {data:c}=await db.from('profiles').select('id,full_name,phone,loyalty_code,role').eq('id',cid).maybeSingle();if(!c||c.role!=='customer')return J({error:'Select a loyalty customer.'},400);const meals=clean(b.meals,Object.keys(mealPrices)),extras=clean(b.extras,Object.keys(extraPrices));const {data:made,error}=await db.rpc('sunday_roast_create_order',{p_customer_id:c.id,p_request_id:'pos-'+crypto.randomUUID(),p_customer_name:String(b.customer_name||c.full_name||'').trim(),p_customer_phone:String(b.customer_phone||c.phone||''),p_collection_date:String(b.collection_date||''),p_collection_slot:String(b.collection_slot||''),p_meals:meals,p_extras:extras});if(error)return J({error:error.message},409);const total=Number(made.total_pence||0),state=String(b.payment_status||'unpaid');let paid=Math.max(0,Math.min(total,Math.round(Number(b.paid_pence)||0)));if(state==='paid_full')paid=total;if(state==='unpaid')paid=0;const now=new Date().toISOString();const {data:order,error:ue}=await db.from('sunday_roast_orders').update({status:'pending',payment_status:'completed',deposit_pence:paid,balance_pence:total-paid,deposit_paid_at:paid?now:null,balance_payment_status:paid>=total?'paid':'unpaid',balance_paid_at:paid>=total?now:null,balance_paid_by:paid>=total?user.id:null,handled_by:user.id,source:'pos',updated_at:now}).eq('id',made.id).select('*').single();if(ue)throw ue;return J({ok:true,order:normal(order)})}
 if(action==='update'){const id=String(b.id||'');const {data:old}=await db.from('sunday_roast_orders').select('*').eq('id',id).maybeSingle();if(!old)return J({error:'Order not found'},404);if(['collected','rejected','no_show'].includes(String(old.status)))return J({error:'Closed orders cannot be edited.'},409);const patch:any={customer_name:String(b.customer_name??old.customer_name).trim().slice(0,120),customer_phone:String(b.customer_phone??old.customer_phone??'').slice(0,40),collection_slot:String(b.collection_slot??old.collection_slot),updated_at:new Date().toISOString(),handled_by:user.id};const {data,error}=await db.from('sunday_roast_orders').update(patch).eq('id',id).select('*').single();if(error)throw error;return J({ok:true,order:normal(data)})}
 if(action==='payment'){const {data,error}=await db.rpc('sunday_roast_confirm_balance_paid',{p_order_id:String(b.id||''),p_handled_by:user.id});if(error)return J({error:error.message},409);return J({ok:true,order:normal(data)})}
 if(action==='status'){let next=String(b.status||'');const id=String(b.id||'');const {data:o}=await db.from('sunday_roast_orders').select('status').eq('id',id).maybeSingle();if(!o)return J({error:'Order not found'},404);if(next==='ready'&&o.status==='pending'){for(const step of ['accept','preparing','ready']){const {error}=await db.rpc('sunday_roast_transition_order',{p_order_id:id,p_action:step,p_reason:'',p_handled_by:user.id});if(error)return J({error:error.message},409)}}else{if(next==='booked')next='accept';const {error}=await db.rpc('sunday_roast_transition_order',{p_order_id:id,p_action:next,p_reason:String(b.reason||''),p_handled_by:user.id});if(error)return J({error:error.message},409)}const {data}=await db.from('sunday_roast_orders').select('*').eq('id',id).single();return J({ok:true,order:normal(data)})}
 return J({error:'Unknown action'},400)
 }catch(e){return J({error:e instanceof Error?e.message:String(e)},500)}});
