(function(){
'use strict';
const C=SundayRoast,A=SundayApi,$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let snapshot=null,currentDate='';
function config(s){return A.config(s)}
function fill(c){snapshot=JSON.stringify(c);$('enabled').checked=c.enabled;$('date').value=c.date;$('override').value=c.override;for(const k of Object.keys(C.meals))$(k).value=Number(c.stock[k]||0);$('slots').value=(c.slots||[]).join('\n');currentDate=c.date}
function totalsHtml(p){const t=p.totals||{},x=t.extras||{};const rows={'Total Sunday dinners':t.dinners||0,'Adult Roast Chicken':t.chicken||0,'Adult Roast Beef':t.beef||0,"Kids' Roast Chicken":t.kids_chicken||0,"Kids' Roast Beef":t.kids_beef||0,'Total chicken meat portions':t.total_chicken_meat||0,'Total beef meat portions':t.total_beef_meat||0,'Extra Chicken':x.chicken||0,'Extra Beef':x.beef||0,'Extra Yorkshire Pudding':x.yorkshire||0,'Extra Gravy':x.gravy||0,'Extra Stuffing':x.stuffing||0,'Extra Roast Potatoes':x.potatoes||0};return Object.entries(rows).map(([k,v])=>`<div class="stat"><strong>${v}</strong>${k}</div>`).join('')}
async function render(date=currentDate){try{const s=await A.settings(date||undefined),c=config(s.settings);if(!snapshot||c.date!==currentDate)fill(c);const p=await A.prep(c.date);$('prepDate').textContent=c.date+' · '+(C.open(c)?'Pre-orders open':'Pre-orders closed');$('totals').innerHTML=totalsHtml(p);$('times').innerHTML=Object.entries(p.totals?.slots||{}).sort().map(([t,v])=>`<div class="row"><strong>${esc(t)}</strong><span>${v.dinners||0} dinners · ${v.chicken||0} adult chicken · ${v.beef||0} adult beef · ${v.kids_chicken||0} kids chicken · ${v.kids_beef||0} kids beef</span></div>`).join('')||'<p>No orders for this Sunday.</p>';$('orders').innerHTML=(p.orders||[]).map(o=>`<article class="order"><h3>SR-${String(o.order_number).padStart(3,'0')} — ${esc(o.customer_name)}</h3><p>${esc(o.customer_phone)}<br>${esc(o.collection_date)} at ${esc(o.collection_slot)}<br><strong>${esc(String(o.status).toUpperCase())}</strong></p>${(o.items||[]).map(i=>`<div>${Number(i.qty)||0} × ${esc(i.name)}</div>`).join('')}<p><strong>${C.money(Number(o.total_pence)||0)}</strong></p>${o.rejection_reason?'<p>'+esc(o.rejection_reason)+'</p>':''}</article>`).join('')||'<p>No pre-orders yet.</p>';$('message').textContent=''}catch(e){$('message').textContent=e.message}}
$('settings').onsubmit=async e=>{e.preventDefault();const c={enabled:$('enabled').checked,date:$('date').value,override:$('override').value,stock:Object.fromEntries(Object.keys(C.meals).map(k=>[k,Number($(k).value)])),slots:$('slots').value.split(/[\n,]/).map(x=>x.trim()).filter(Boolean).sort()};try{C.validateConfig(c);if(c.date<C.london().slice(0,10))throw Error('Choose a current or future Sunday.');await A.setSettings(c.date,c);fill(c);$('message').textContent='Test Sunday settings saved.';await render(c.date)}catch(e){$('message').textContent=e.message}};
$('filterDate').onchange=async()=>{const v=$('filterDate').value;if(v){currentDate=v;snapshot=null;await render(v)}};
async function boot(){try{const s=await A.status();const c=s.config;fill(c);$('filterDate').innerHTML=`<option value="${esc(c.date)}">${esc(c.date)}</option>`;await render(c.date)}catch(e){$('message').textContent=e.message}}
boot();setInterval(()=>render(currentDate),10000);
})();
