(function(){
'use strict';const C=SundayRoast,S=SundayStore,$=id=>document.getElementById(id),d=C.empty();let requestId=crypto.randomUUID(),pending=false,reviewedDate=null;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const photos={chicken:'https://www.nestleprofessional.co.uk/sites/default/files/styles/np_recipe_detail_2x/public/2022-04/roast-chicken.png?itok=QZPz3t1Q',beef:'https://drizzleanddip.com/wp-content/uploads/2023/04/O6A9029.jpg'};
const photoFor=k=>photos[k.includes('beef')?'beef':'chicken'];
function counter(kind,key){const label=(kind==='meals'?C.meals:C.extras)[key].name;return `<div class="counter"><button type="button" data-kind="${kind}" data-key="${key}" data-delta="-1" aria-label="Remove ${label}">−</button><output id="q-${kind}-${key}" aria-label="${label} quantity">0</output><button type="button" data-kind="${kind}" data-key="${key}" data-delta="1" aria-label="Add ${label}">+</button></div>`}
$('meals').innerHTML=Object.entries(C.meals).map(([key,m])=>`<article class="card meal"><img src="${photoFor(key)}" alt="${m.name} serving suggestion"><div class="body"><span class="eyebrow">${m.group==='kids'?'Kids Sunday':'Sunday favourite'}</span><h2>${m.name}</h2><div class="price">${C.money(m.price)}</div>${m.group==='kids'?'<p class="muted">Smaller kids portion with the same Sunday trimmings.</p>':''}<p id="stock-${key}" class="muted"></p>${counter('meals',key)}</div></article>`).join('');
$('extras').innerHTML=Object.entries(C.extras).map(([key,m])=>`<div class="extra"><div><strong>${m.name}</strong><br><small>${C.money(m.price)}</small></div>${counter('extras',key)}</div>`).join('');$('included').innerHTML=C.included.map(x=>`<li>${x}</li>`).join('');
function fields(){d.slot=$('slot').value;d.name=$('name').value;d.phone=$('phone').value}
function summary(){return C.lines(d).map(i=>`<div class="row"><span>${i.qty} × ${i.name}</span><span>${C.money(i.price*i.qty)}</span></div>`).join('')||'<p class="muted">Choose a dinner to get started.</p>'}
function render(){const {config:c,orders}=S.read(),isOpen=C.open(c);$('dateLabel').textContent=c.enabled?'Collection: '+new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'Europe/London'}).format(new Date(c.date+'T12:00:00Z')):'Sunday Roast ordering is not currently enabled';$('closed').classList.toggle('hidden',isOpen);$('closed').textContent='Pre-orders closed for this Sunday';$('cutoff').textContent='Pre-order by Friday, '+C.cutoff(c.date).slice(0,10)+' at 8:00 PM (UK time).';
const available=c.slots.filter(t=>`${c.date}T${t}`>C.london());const slotHtml='<option value="">Choose collection time</option>'+available.map(t=>`<option value="${t}">${t}</option>`).join('');if($('slot').innerHTML!==slotHtml){$('slot').innerHTML=slotHtml;$('slot').value=available.includes(d.slot)?d.slot:''}if(!$('slot').value)d.slot='';
for(const k of Object.keys(C.meals)){$('stock-'+k).textContent=c.stock[k]===0?'SOLD OUT':c.stock[k]+' available';$('stock-'+k).classList.toggle('sold',c.stock[k]===0)}
for(const b of document.querySelectorAll('[data-delta]')){const {kind,key,delta}=b.dataset,q=d[kind][key],max=kind==='meals'?Math.min(50,c.stock[key]):50;b.disabled=pending||(delta==='1'?(!isOpen||q>=max):q===0);$('q-'+kind+'-'+key).textContent=q}
$('summary').innerHTML=summary();$('total').textContent=C.money(C.total(d));$('review').disabled=pending||!isOpen||!C.lines(d).some(i=>i.kind==='meals');
$('history').innerHTML=orders.length?orders.slice().reverse().map(o=>`<article class="order"><h3>${esc(o.order_number)} · ${esc(o.status.toUpperCase())}</h3><p>${esc(o.collection_time)}</p>${o.items.map(i=>`<div>${i.qty} × ${esc(i.name)}</div>`).join('')}<p><strong>${C.money(o.total_pence)}</strong></p>${o.rejection_reason?'<p>'+esc(o.rejection_reason)+'</p>':''}</article>`).join(''):'<p class="muted">Your test pre-orders will appear here.</p>';
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-delta]');if(!b||b.disabled)return;const {kind,key,delta}=b.dataset;d[kind][key]+=Number(delta);requestId=crypto.randomUUID();render()});for(const id of ['slot','name','phone'])$(id).addEventListener('change',()=>{fields();requestId=crypto.randomUUID()});
$('review').onclick=()=>{fields();try{C.validate(S.read().config,d);reviewedDate=S.read().config.date;$('message').textContent='';$('confirmError').textContent='';$('reviewBody').innerHTML=`<p>${esc(S.read().config.date)} at ${esc(d.slot)} (UK)</p>`+summary()+`<div class="row total"><span>Total</span><span>${C.money(C.total(d))}</span></div>`;$('confirm').showModal()}catch(e){$('message').textContent=e.message}};
$('cancel').onclick=()=>{if(!pending)$('confirm').close()};$('confirm').addEventListener('cancel',e=>{if(pending)e.preventDefault()});
$('place').onclick=async()=>{if(pending)return;pending=true;$('place').disabled=true;$('cancel').disabled=true;try{const order=await S.mutate(s=>{if(s.config.date!==reviewedDate)throw Error('The collection date changed. Go back and review again.');return C.create(s,d,requestId)});Object.assign(d,C.empty());$('confirm').close();$('message').textContent='Test pre-order '+order.order_number+' saved. Awaiting acceptance in the test KDS.';requestId=crypto.randomUUID()}catch(e){$('confirmError').textContent=e.message}finally{pending=false;$('place').disabled=false;$('cancel').disabled=false;render()}};
window.addEventListener('storage',render);window.addEventListener('sundaychange',render);setInterval(render,10000);render();
})();
