const SUPABASE_URL='https://bpnkouymdvcogeaqjmxl.supabase.co';
const SUPABASE_KEY='sb_publishable_v6rJbF4IfGZTKtbuQtmsmQ_lS3sXWFa';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let currentUser=null,profile=null,loyalty=null,staffOffers=[],staffMembers=[],currentSpinPrize=null,spinPromotionEnabled=false;
const $=id=>document.getElementById(id);
function status(msg,type='ok'){if(!$('status'))return;$('status').innerHTML=`<div class="status ${type}">${msg}</div>`;setTimeout(()=>{if($('status'))$('status').innerHTML=''},5000)}
function cleanCode(v){return(v||'').replace(/\D/g,'').slice(0,6)}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function hasPerm(name){return profile?.role==='admin'||!!profile?.staff_permissions?.[name]}
function toggleAuth(join){$('loginPane').classList.toggle('hidden',join);$('signupPane').classList.toggle('hidden',!join);$('loginTab').classList.toggle('active',!join);$('signupTab').classList.toggle('active',join)}
$('loginTab').onclick=()=>toggleAuth(false);$('signupTab').onclick=()=>toggleAuth(true);

let scannerStream=null,scannerTimer=null,scannerDetector=null,scannerBusy=false;
function extractDextersCode(raw){const m=String(raw||'').trim().match(/(?:DEXTERS\s*:\s*)?(\d{6})$/i);return m?m[1]:''}
async function stopScanner(){if(scannerTimer){clearTimeout(scannerTimer);scannerTimer=null}if(scannerStream){scannerStream.getTracks().forEach(t=>t.stop());scannerStream=null}scannerBusy=false;if($('scannerVideo'))$('scannerVideo').srcObject=null;if($('scannerBox'))$('scannerBox').classList.add('hidden')}
async function scanFrame(){if(!scannerStream||scannerBusy)return;scannerBusy=true;try{const codes=await scannerDetector.detect($('scannerVideo'));if(codes?.length){const code=extractDextersCode(codes[0].rawValue);if(code){$('staffCode').value=code;await stopScanner();status('Customer QR scanned successfully.');await lookupStaffCustomer(code);return}}}catch(e){}scannerBusy=false;if(scannerStream)scannerTimer=setTimeout(scanFrame,300)}
async function startScanner(){if(!('BarcodeDetector'in window))return status('QR camera scanning is not supported by this browser. Please enter the 6-digit code manually.','err');try{const formats=await BarcodeDetector.getSupportedFormats();if(!formats.includes('qr_code'))return status('QR scanning is not supported by this browser. Please enter the 6-digit code manually.','err');await stopScanner();scannerDetector=new BarcodeDetector({formats:['qr_code']});scannerStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});$('scannerBox').classList.remove('hidden');$('scannerVideo').srcObject=scannerStream;await $('scannerVideo').play();scannerBusy=false;scanFrame()}catch(e){await stopScanner();status(e?.name==='NotAllowedError'?'Camera permission was blocked. Allow camera access, or enter the 6-digit code manually.':'Could not start the camera. Please enter the 6-digit code manually.','err')}}
$('scanQrBtn').onclick=startScanner;$('stopScanBtn').onclick=stopScanner;
$('staffCode').oninput=async e=>{e.target.value=cleanCode(e.target.value);$('staffCustomer').classList.add('hidden');$('staffSpinPrize').classList.add('hidden');currentSpinPrize=null;$('redeemBtn').disabled=true;$('redeemSpinBtn').disabled=true;if(e.target.value.length===6)await lookupStaffCustomer(e.target.value)};

async function login(){const email=$('loginEmail').value.trim(),password=$('loginPassword').value;if(!email||!password)return status('Enter your email and password.','err');$('loginBtn').disabled=true;const {error}=await db.auth.signInWithPassword({email,password});$('loginBtn').disabled=false;if(error)return status(error.message,'err');await loadSession()}
async function signup(){const name=$('fullName').value.trim(),phone=$('phone').value.trim(),email=$('signupEmail').value.trim(),password=$('signupPassword').value;if(!name||!email||password.length<6)return status('Please enter your name, email and a password of at least 6 characters.','err');const {data,error}=await db.auth.signUp({email,password,options:{data:{full_name:name,phone}}});if(error)return status(error.message,'err');if(data.session){await loadSession();status('Welcome to Dexters Loyalty!')}else status('Account created. Check your email if Supabase asks you to confirm it.')}
$('loginBtn').onclick=login;$('signupBtn').onclick=signup;

async function loadSession(){const {data:{session}}=await db.auth.getSession();currentUser=session?.user||null;$('authView').classList.toggle('hidden',!!currentUser);$('appView').classList.toggle('hidden',!currentUser);$('bottomNav').classList.toggle('hidden',!currentUser);if(!currentUser)return;await refreshData()}
async function refreshData(){const {data:p,error:pe}=await db.from('profiles').select('id,full_name,phone,role,loyalty_code,staff_permissions').eq('id',currentUser.id).single();if(pe){status('Your account is signed in, but the loyalty profile is not ready yet. Please try again in a moment.','err');return}profile=p;const {data:l}=await db.from('loyalty_accounts').select('stamps,reward_ready').eq('user_id',currentUser.id).single();loyalty=l||{stamps:0,reward_ready:false};await loadSpinPromotionStatus();render();await loadOffers();if(spinPromotionEnabled)await loadSpinStatus();else clearSpinUi();if(profile.role==='admin'||hasPerm('manage_offers'))await loadStaffOffers();if(profile.role==='admin'||hasPerm('redeem_spin_prizes')){await loadSpinWinners();renderSpinControl()}if(profile.role==='admin')await loadStaffMembers()}
function render(){const n=profile.full_name||currentUser.email.split('@')[0];$('greeting').textContent=n.split(' ')[0];$('accountName').value=profile.full_name||'';$('accountPhone').value=profile.phone||'';$('accountEmail').textContent=currentUser.email;const staff=['staff','admin'].includes(profile.role),anyStaffAccess=profile.role==='admin'||['loyalty_lookup','add_stamps','redeem_rewards','manage_offers','redeem_spin_prizes'].some(hasPerm);$('staffNav').classList.toggle('hidden',!staff||!anyStaffAccess);$('roleBadge').classList.toggle('hidden',!staff);$('roleBadge').textContent=profile.role.toUpperCase();$('staffLoyaltyCard').classList.toggle('hidden',!(profile.role==='admin'||hasPerm('loyalty_lookup')||hasPerm('add_stamps')||hasPerm('redeem_rewards')||hasPerm('redeem_spin_prizes')));$('staffOffersCard').classList.toggle('hidden',!(profile.role==='admin'||hasPerm('manage_offers')));$('staffManagerCard').classList.toggle('hidden',profile.role!=='admin');$('staffSpinWinnersCard').classList.toggle('hidden',!(profile.role==='admin'||hasPerm('redeem_spin_prizes')));$('staffSpinControlCard').classList.toggle('hidden',!(profile.role==='admin'||hasPerm('redeem_spin_prizes')));const canLookup=profile.role==='admin'||hasPerm('loyalty_lookup')||hasPerm('add_stamps')||hasPerm('redeem_rewards')||hasPerm('redeem_spin_prizes');$('scanQrBtn').disabled=!canLookup;$('staffCode').disabled=!canLookup;$('addStampBtn').classList.toggle('hidden',!(profile.role==='admin'||hasPerm('add_stamps')));$('redeemBtn').classList.toggle('hidden',!(profile.role==='admin'||hasPerm('redeem_rewards')));const spinNav=document.querySelector('[data-page="spinPage"]');if(spinNav)spinNav.classList.toggle('hidden',!spinPromotionEnabled);if(!spinPromotionEnabled&&!$('spinPage').classList.contains('hidden'))showPage('homePage');const s=loyalty?.stamps||0;$('stampText').textContent=`${s} / 9`;$('progressBar').style.width=`${Math.min(100,s/9*100)}%`;$('stamps').innerHTML='';for(let i=1;i<=9;i++){const d=document.createElement('div');d.className='stamp '+(i<=s?'on':'');d.textContent=i<=s?'☕':i;$('stamps').appendChild(d)}$('stampMessage').textContent=s>=9?'Your FREE coffee is ready! Show your code to staff to redeem.':`${9-s} stamp${9-s===1?'':'s'} to your free coffee.`;$('rewardText').textContent=s>=9?'🎉 Reward ready — your next coffee is FREE.':'Collect all 9 stamps to unlock your free coffee.';const code=profile.loyalty_code||'------';$('loyaltyCode').textContent=code;$('qr').innerHTML='';if(code!=='------')new QRCode($('qr'),{text:`DEXTERS:${code}`,width:190,height:190,correctLevel:QRCode.CorrectLevel.H})}
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));$(id).classList.remove('hidden');document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));document.querySelector(`.nav button[data-page="${id}"]`)?.classList.add('active')}

async function loadOffers(){const {data,error}=await db.from('offers_v2').select('id,title,description,image_url,expires_at').eq('active',true).or(`expires_at.is.null,expires_at.gt.${new Date().toISOString()}`).order('created_at',{ascending:false}).limit(10);if(error){$('offers').innerHTML='<p class="muted">Offers are temporarily unavailable.</p>';return}$('offers').innerHTML=data?.length?data.map(o=>`<div class="offer">${o.image_url?`<img src="${escapeHtml(o.image_url)}" alt="${escapeHtml(o.title)}">`:''}<strong>${escapeHtml(o.title)}</strong>${o.description?`<div class="muted tiny">${escapeHtml(o.description)}</div>`:''}${o.expires_at?`<div class="offer-meta">Ends ${new Date(o.expires_at).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'})}</div>`:''}</div>`).join(''):'<p class="muted">No current offers.</p>'}

async function loadSpinPromotionStatus(){const {data,error}=await db.rpc('spin_wheel_is_enabled');spinPromotionEnabled=!error&&data===true;return spinPromotionEnabled}
function renderSpinControl(){if(!$('spinPromoStatus'))return;const allowed=profile?.role==='admin'||hasPerm('redeem_spin_prizes');$('staffSpinControlCard').classList.toggle('hidden',!allowed);$('spinPromoStatus').textContent=spinPromotionEnabled?'Free Spin is visible to customers':'Free Spin is hidden from customers';$('spinPromoPill').textContent=spinPromotionEnabled?'ON':'OFF';$('spinPromoPill').className='pill '+(spinPromotionEnabled?'live':'used');$('toggleSpinPromoBtn').textContent=spinPromotionEnabled?'Hide Free Spin':'Start Free Spin Promotion';$('toggleSpinPromoBtn').className='btn '+(spinPromotionEnabled?'danger':'primary');$('toggleSpinPromoBtn').disabled=!allowed}
async function toggleSpinPromotion(){const next=!spinPromotionEnabled,verb=next?'start the Free Spin promotion':'hide Free Spin from customers';if(!window.confirm(`Are you sure you want to ${verb}?`))return;$('toggleSpinPromoBtn').disabled=true;const {data,error}=await db.rpc('staff_spin_wheel_set_enabled',{p_enabled:next});if(error){$('toggleSpinPromoBtn').disabled=false;return status(error.message,'err')}spinPromotionEnabled=data===true;render();renderSpinControl();if(spinPromotionEnabled)await loadSpinStatus();else clearSpinUi();status(spinPromotionEnabled?'Free Spin promotion is now LIVE.':'Free Spin is now hidden from customers.')}
$('toggleSpinPromoBtn').onclick=toggleSpinPromotion;
function clearSpinUi(){$('spinResult').textContent='';$('spinNext').textContent='';$('spinBtn').disabled=true;$('mySpinPrizeCard').classList.add('hidden')}
function formatNextSpin(ts){if(!ts)return'';return`Next free spin: ${new Date(ts).toLocaleString('en-GB',{weekday:'short',hour:'2-digit',minute:'2-digit'})}`}
async function loadSpinStatus(){if(!currentUser||!spinPromotionEnabled)return clearSpinUi();const {data,error}=await db.rpc('spin_wheel_my_status');if(error){$('spinResult').textContent='Free Spin is temporarily unavailable.';$('spinBtn').disabled=true;return}const r=Array.isArray(data)?data[0]:data;if(!r)return;$('spinBtn').disabled=!!r.has_spun_today;$('spinNext').textContent=r.has_spun_today?formatNextSpin(r.next_spin_at):'Your free spin is ready.';$('mySpinPrizeCard').classList.toggle('hidden',!(r.has_spun_today&&r.is_win&&!r.redeemed));if(r.has_spun_today&&r.is_win){$('mySpinPrizeName').textContent=r.prize_name||'Dexter’s meal';$('spinResult').textContent=r.redeemed?'Prize already redeemed.':`🎉 WINNER! ${r.prize_name||'Dexter’s meal'}`}else if(r.has_spun_today)$('spinResult').textContent='No win this time — try again tomorrow!';else $('spinResult').textContent=''}
let spinAnimating=false;async function spinWheel(){if(!spinPromotionEnabled)return status('Free Spin promotion is not active.','err');if(spinAnimating||$('spinBtn').disabled)return;spinAnimating=true;$('spinBtn').disabled=true;$('spinResult').textContent='';$('spinWheel').style.transform=`rotate(${1440+Math.floor(Math.random()*720)}deg)`;const {data,error}=await db.rpc('spin_wheel_spin');if(error){spinAnimating=false;await loadSpinPromotionStatus();render();renderSpinControl();$('spinBtn').disabled=!spinPromotionEnabled;return status(error.message||'Could not spin. Please try again.','err')}const r=Array.isArray(data)?data[0]:data;setTimeout(()=>{spinAnimating=false;$('spinNext').textContent=formatNextSpin(r.next_spin_at);if(r.is_win){$('spinResult').textContent=`🎉 WINNER! ${r.prize_name||'Dexter’s meal'}`;$('mySpinPrizeName').textContent=r.prize_name||'Dexter’s meal';$('mySpinPrizeCard').classList.remove('hidden')}else{$('spinResult').textContent='No win this time — try again tomorrow!';$('mySpinPrizeCard').classList.add('hidden')}},4000)}
$('spinBtn').onclick=spinWheel;

async function loadSpinWinners(){if(!(profile?.role==='admin'||hasPerm('redeem_spin_prizes')))return;const {data,error}=await db.rpc('staff_spin_winners');if(error){$('staffSpinWinnersList').innerHTML=`<p class="muted">Could not load winners: ${escapeHtml(error.message)}</p>`;return}$('staffSpinWinnersList').innerHTML=data?.length?data.map(r=>`<div class="winner-row"><div class="row between"><strong>${escapeHtml(r.customer_name||'Customer')}</strong><span class="pill ${r.redeemed?'used':'live'}">${r.redeemed?'REDEEMED':'WAITING'}</span></div><div>${escapeHtml(r.prize_name||'Dexter’s meal')}</div><div class="tiny muted">Loyalty code ${escapeHtml(r.loyalty_code||'')}</div></div>`).join(''):'<p class="muted">No Spin & Win winners yet.</p>'}
$('refreshSpinWinnersBtn').onclick=loadSpinWinners;
async function lookupStaffSpinPrize(code){currentSpinPrize=null;$('staffSpinPrize').classList.add('hidden');$('redeemSpinBtn').disabled=true;if(!(profile?.role==='admin'||hasPerm('redeem_spin_prizes')))return;const {data,error}=await db.rpc('staff_spin_lookup',{p_loyalty_code:code});if(error)return;const r=Array.isArray(data)?data[0]:data;if(!r)return;currentSpinPrize=r;$('staffSpinPrizeName').textContent=r.prize_name||'Dexter’s meal';$('staffSpinPrize').classList.remove('hidden');$('redeemSpinBtn').disabled=false}
async function redeemSpinPrize(){const code=cleanCode($('staffCode').value);if(!currentSpinPrize||code.length!==6)return status('Scan the winning customer’s loyalty QR first.','err');const prize=currentSpinPrize.prize_name||'Dexter’s meal';if(!window.confirm(`Confirm Spin & Win prize: ${prize}?`))return;$('redeemSpinBtn').disabled=true;const {error}=await db.rpc('staff_redeem_spin_prize',{p_loyalty_code:code,p_spin_id:currentSpinPrize.spin_id});if(error){$('redeemSpinBtn').disabled=false;return status(error.message,'err')}status(`Prize confirmed and redeemed: ${prize}`);currentSpinPrize=null;$('staffSpinPrize').classList.add('hidden');await loadSpinWinners()}
$('redeemSpinBtn').onclick=redeemSpinPrize;

function offerImagePathFromUrl(url){if(!url)return'';const marker='/storage/v1/object/public/offer-images/';const i=url.indexOf(marker);return i>=0?decodeURIComponent(url.slice(i+marker.length)):''}
function resetOfferForm(){$('offerId').value='';$('offerTitle').value='';$('offerDescription').value='';$('offerImage').value='';$('offerExpiry').value='';$('offerActive').checked=true;$('saveOfferBtn').textContent='Publish offer';$('cancelOfferEditBtn').classList.add('hidden')}
async function uploadOfferImage(file){if(!file)return null;if(!file.type.startsWith('image/'))throw new Error('Please choose an image file.');if(file.size>5*1024*1024)throw new Error('Offer image must be under 5MB.');const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase(),path=`${currentUser.id}/${Date.now()}-${Math.random().toString(36).slice(2,8)}.${ext}`;const {error}=await db.storage.from('offer-images').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(error)throw error;return db.storage.from('offer-images').getPublicUrl(path).data.publicUrl}
async function loadStaffOffers(){const {data,error}=await db.from('offers_v2').select('id,title,description,image_url,active,expires_at,created_at').order('created_at',{ascending:false});if(error){$('staffOffersList').innerHTML=`<p class="muted">Could not load offers: ${escapeHtml(error.message)}</p>`;return}staffOffers=data||[];$('staffOffersList').innerHTML=staffOffers.length?staffOffers.map(o=>`<div class="offer">${o.image_url?`<img src="${escapeHtml(o.image_url)}" alt="${escapeHtml(o.title)}">`:''}<div class="row between"><strong>${escapeHtml(o.title)}</strong><span class="staff-badge">${o.active?'LIVE':'OFF'}</span></div>${o.description?`<div class="muted tiny">${escapeHtml(o.description)}</div>`:''}<div class="offer-meta">${o.expires_at?`Expires ${new Date(o.expires_at).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'})}`:'No expiry'}</div><div class="offer-actions"><button class="btn secondary" data-edit-offer="${o.id}">Edit</button><button class="btn ${o.active?'danger':'primary'}" data-toggle-offer="${o.id}">${o.active?'Unpublish':'Publish'}</button><button class="btn danger" data-delete-offer="${o.id}">Delete</button></div></div>`).join(''):'<p class="muted">No offers created yet.</p>';document.querySelectorAll('[data-edit-offer]').forEach(b=>b.onclick=()=>editOffer(b.dataset.editOffer));document.querySelectorAll('[data-toggle-offer]').forEach(b=>b.onclick=()=>toggleOffer(b.dataset.toggleOffer));document.querySelectorAll('[data-delete-offer]').forEach(b=>b.onclick=()=>deleteOffer(b.dataset.deleteOffer))}
function editOffer(id){const o=staffOffers.find(x=>x.id===id);if(!o)return;$('offerId').value=o.id;$('offerTitle').value=o.title||'';$('offerDescription').value=o.description||'';$('offerExpiry').value=o.expires_at?new Date(new Date(o.expires_at).getTime()-new Date(o.expires_at).getTimezoneOffset()*60000).toISOString().slice(0,16):'';$('offerActive').checked=!!o.active;$('saveOfferBtn').textContent='Save changes';$('cancelOfferEditBtn').classList.remove('hidden');$('staffOffersCard').scrollIntoView({behavior:'smooth',block:'start'})}
async function saveOffer(){if(!(profile?.role==='admin'||hasPerm('manage_offers')))return status('You do not have permission to manage offers.','err');const title=$('offerTitle').value.trim(),description=$('offerDescription').value.trim();if(!title)return status('Enter an offer title.','err');const id=$('offerId').value,existing=id?staffOffers.find(x=>x.id===id):null;$('saveOfferBtn').disabled=true;try{let imageUrl=existing?.image_url||null;const file=$('offerImage').files?.[0];if(file)imageUrl=await uploadOfferImage(file);const row={title,description:description||null,image_url:imageUrl,active:$('offerActive').checked,expires_at:$('offerExpiry').value?new Date($('offerExpiry').value).toISOString():null,updated_at:new Date().toISOString()};const result=id?await db.from('offers_v2').update(row).eq('id',id):await db.from('offers_v2').insert(row);if(result.error)throw result.error;if(existing?.image_url&&file&&existing.image_url!==imageUrl){const old=offerImagePathFromUrl(existing.image_url);if(old)await db.storage.from('offer-images').remove([old])}status(id?'Offer updated.':'Offer published.');resetOfferForm();await loadStaffOffers();await loadOffers()}catch(e){status(e.message||'Could not save offer.','err')}finally{$('saveOfferBtn').disabled=false}}
async function toggleOffer(id){const o=staffOffers.find(x=>x.id===id);if(!o)return;const {error}=await db.from('offers_v2').update({active:!o.active,updated_at:new Date().toISOString()}).eq('id',id);if(error)return status(error.message,'err');status(o.active?'Offer unpublished.':'Offer published.');await loadStaffOffers();await loadOffers()}
async function deleteOffer(id){const o=staffOffers.find(x=>x.id===id);if(!o||!window.confirm(`Delete offer “${o.title}”?`))return;const {error}=await db.from('offers_v2').delete().eq('id',id);if(error)return status(error.message,'err');const path=offerImagePathFromUrl(o.image_url);if(path)await db.storage.from('offer-images').remove([path]);status('Offer deleted.');if($('offerId').value===id)resetOfferForm();await loadStaffOffers();await loadOffers()}
$('saveOfferBtn').onclick=saveOffer;$('cancelOfferEditBtn').onclick=resetOfferForm;

function readStaffPerms(){return{loyalty_lookup:$('permLookup').checked,add_stamps:$('permStamp').checked,redeem_rewards:$('permRedeem').checked,manage_offers:$('permOffers').checked,redeem_spin_prizes:$('permSpin').checked}}
function resetStaffForm(){$('staffMemberId').value='';$('newStaffName').value='';$('newStaffEmail').value='';$('newStaffEmail').disabled=false;$('newStaffPhone').value='';$('newStaffPassword').value='';$('newStaffPasswordWrap').classList.remove('hidden');$('permLookup').checked=true;$('permStamp').checked=true;$('permRedeem').checked=true;$('permOffers').checked=false;$('permSpin').checked=true;$('saveStaffBtn').textContent='Add staff member';$('cancelStaffEditBtn').classList.add('hidden')}
async function callStaffAdmin(body){const {data,error}=await db.functions.invoke('admin-manage-staff',{body});if(error)throw new Error(error.context?.body?.error||error.message||'Could not manage staff.');if(data?.error)throw new Error(data.error);return data}
async function loadStaffMembers(){if(profile?.role!=='admin')return;try{const data=await callStaffAdmin({action:'list'});staffMembers=data.staff||[];$('staffMembersList').innerHTML=staffMembers.length?staffMembers.map(s=>`<div class="offer"><div class="row between"><strong>${escapeHtml(s.full_name||s.email||'Staff')}</strong><span class="staff-badge">${escapeHtml(String(s.role).toUpperCase())}</span></div><div class="tiny muted">${escapeHtml(s.email||'')}</div>${s.role==='staff'?`<div class="tiny" style="margin-top:8px">${['loyalty_lookup','add_stamps','redeem_rewards','manage_offers','redeem_spin_prizes'].filter(k=>s.staff_permissions?.[k]).map(k=>({loyalty_lookup:'Scan customers',add_stamps:'Add stamps',redeem_rewards:'Redeem rewards',manage_offers:'Manage offers',redeem_spin_prizes:'Spin prizes'}[k])).join(' • ')||'No permissions'}</div><div class="offer-actions"><button class="btn secondary" data-edit-staff="${s.id}">Edit permissions</button><button class="btn danger" data-remove-staff="${s.id}">Remove staff access</button></div>`:'<div class="tiny muted" style="margin-top:8px">Administrator — full access</div>'}</div>`).join(''):'<p class="muted">No staff accounts yet.</p>';document.querySelectorAll('[data-edit-staff]').forEach(b=>b.onclick=()=>editStaffMember(b.dataset.editStaff));document.querySelectorAll('[data-remove-staff]').forEach(b=>b.onclick=()=>removeStaffMember(b.dataset.removeStaff))}catch(e){$('staffMembersList').innerHTML=`<p class="muted">Could not load staff: ${escapeHtml(e.message)}</p>`}}
function editStaffMember(id){const s=staffMembers.find(x=>x.id===id);if(!s||s.role!=='staff')return;$('staffMemberId').value=s.id;$('newStaffName').value=s.full_name||'';$('newStaffEmail').value=s.email||'';$('newStaffEmail').disabled=true;$('newStaffPhone').value=s.phone||'';$('newStaffPasswordWrap').classList.add('hidden');$('permLookup').checked=!!s.staff_permissions?.loyalty_lookup;$('permStamp').checked=!!s.staff_permissions?.add_stamps;$('permRedeem').checked=!!s.staff_permissions?.redeem_rewards;$('permOffers').checked=!!s.staff_permissions?.manage_offers;$('permSpin').checked=!!s.staff_permissions?.redeem_spin_prizes;$('saveStaffBtn').textContent='Save permissions';$('cancelStaffEditBtn').classList.remove('hidden');$('staffManagerCard').scrollIntoView({behavior:'smooth',block:'start'})}
async function saveStaffMember(){if(profile?.role!=='admin')return status('Admin access required.','err');const id=$('staffMemberId').value,name=$('newStaffName').value.trim(),email=$('newStaffEmail').value.trim(),phone=$('newStaffPhone').value.trim(),password=$('newStaffPassword').value;if(!name||!email)return status('Enter the staff member’s name and email.','err');if(!id&&password.length<8)return status('Temporary password must be at least 8 characters.','err');$('saveStaffBtn').disabled=true;try{await callStaffAdmin(id?{action:'update',id,full_name:name,phone,permissions:readStaffPerms()}:{action:'create',full_name:name,email,phone,password,permissions:readStaffPerms()});status(id?'Staff permissions updated.':'Staff account created.');resetStaffForm();await loadStaffMembers()}catch(e){status(e.message,'err')}finally{$('saveStaffBtn').disabled=false}}
async function removeStaffMember(id){const s=staffMembers.find(x=>x.id===id);if(!s||!window.confirm(`Remove staff access for ${s.full_name||s.email}?`))return;try{await callStaffAdmin({action:'remove',id});status('Staff access removed.');await loadStaffMembers()}catch(e){status(e.message,'err')}}
$('saveStaffBtn').onclick=saveStaffMember;$('cancelStaffEditBtn').onclick=resetStaffForm;

$('saveProfileBtn').onclick=async()=>{const {error}=await db.from('profiles').update({full_name:$('accountName').value.trim(),phone:$('accountPhone').value.trim()}).eq('id',currentUser.id);if(error)return status(error.message,'err');status('Details saved');await refreshData()};
$('deleteAccountBtn').onclick=async()=>{if(!currentUser)return;if(!window.confirm('Delete your Dexters Loyalty account? This permanently removes the account and loyalty progress and cannot be undone.'))return;$('deleteAccountBtn').disabled=true;const {error}=await db.functions.invoke('delete-my-account',{body:{confirm:true}});if(error){$('deleteAccountBtn').disabled=false;return status('Could not delete your account. Please try again.','err')}await db.auth.signOut();profile=loyalty=currentUser=null;status('Your account has been deleted.');await loadSession()};
$('logoutBtn').onclick=async()=>{await stopScanner();await db.auth.signOut();profile=loyalty=currentUser=null;await loadSession()};

async function lookupStaffCustomer(code){const {data,error}=await db.rpc('staff_lookup_customer',{p_loyalty_code:code});if(error){$('staffCustomer').classList.add('hidden');return status(error.message,'err')}const c=Array.isArray(data)?data[0]:data;if(!c){$('staffCustomer').classList.add('hidden');return status('Customer not found.','err')}$('staffCustomerName').textContent=c.full_name||'Customer';$('staffCustomerCode').textContent=c.loyalty_code;$('staffCustomerStamps').textContent=`${c.stamps} / 9 stamps`;$('staffCustomerReward').textContent=c.reward_ready?'FREE coffee ready to redeem':'Reward not ready yet';$('redeemBtn').disabled=!c.reward_ready;$('staffCustomer').classList.remove('hidden');await lookupStaffSpinPrize(code)}
async function staffAction(kind){const code=cleanCode($('staffCode').value);if(code.length!==6)return status('Enter the customer’s 6-digit code.','err');const fn=kind==='stamp'?'staff_add_stamp':'staff_redeem_reward';const {error}=await db.rpc(fn,{p_loyalty_code:code});if(error)return status(error.message,'err');status(kind==='stamp'?'Stamp added successfully.':'Free coffee redeemed.');await lookupStaffCustomer(code)}
$('redeemBtn').disabled=true;$('addStampBtn').onclick=()=>{const code=cleanCode($('staffCode').value);if(code.length!==6||$('staffCustomer').classList.contains('hidden'))return status('Scan or enter a valid customer first.','err');if(window.confirm(`Add 1 coffee stamp to ${$('staffCustomerName').textContent||'this customer'}?`))staffAction('stamp')};$('redeemBtn').onclick=()=>{if($('redeemBtn').disabled)return;if(window.confirm(`Redeem ${$('staffCustomerName').textContent||'this customer'}'s FREE coffee?`))staffAction('redeem')};

document.querySelectorAll('.nav button').forEach(b=>b.onclick=async()=>{if(!b.dataset.page)return;if(b.dataset.page==='spinPage'&&!spinPromotionEnabled)return;if(b.dataset.page!=='staffPage')await stopScanner();showPage(b.dataset.page);if(b.dataset.page==='staffPage'&&(profile?.role==='admin'||hasPerm('redeem_spin_prizes'))){await loadSpinPromotionStatus();render();renderSpinControl()}});
db.auth.onAuthStateChange(()=>setTimeout(loadSession,0));loadSession();
