import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const J=(body:any,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const REASONS=["Restaurant has closed early","Item unavailable","Kitchen too busy to accept this order","Equipment issue","Requested collection time unavailable","Unable to fulfil order today","Other"];
const cleanPhone=(v:any)=>String(v||'').trim().replace(/[^0-9+()\-\s]/g,'').slice(0,40);
const gbp=(v:any)=>Number(v||0);
function ingredientList(desc:any){if(!desc)return[];let s=String(desc).replace(/;.*$/,'').replace(/\.$/,'').trim();if(!s)return[];s=s.replace(/\band\b/gi,',').replace(/\s*&\s*/g,',');const parts=s.split(',').map((x:string)=>x.trim()).filter(Boolean).map((x:string)=>x.replace(/^(with|served with|topped with|finished with)\s+/i,'').trim());const bad=/^(freshly cooked|large freshly cooked|crispy battered fish|two crispy battered fish)$/i;return [...new Set(parts.filter((x:string)=>x.length>1&&!bad.test(x)))].slice(0,14)}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))return J({error:'Not authenticated'},401);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const uc=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:{user}}=await uc.auth.getUser();if(!user)return J({error:'Invalid session'},401);const db=createClient(url,service);const {data:profile}=await db.from('profiles').select('role,full_name,phone').eq('id',user.id).single();const role=profile?.role||'customer',admin=role==='admin',staff=role==='staff';let b:any={};try{b=await req.json()}catch{return J({error:'Invalid request'},400)}const action=String(b.action||'');
if(action==='status'){const {data:s}=await db.from('collection_ordering_settings').select('enabled,updated_at').eq('id',1).single();return J({enabled:!!s?.enabled,updated_at:s?.updated_at,rejection_reasons:REASONS,role,customer:{full_name:profile?.full_name||'',phone:profile?.phone||''}})}
if(action==='set_enabled'){if(!admin)return J({error:'Admin access required'},403);const enabled=!!b.enabled;const {error}=await db.from('collection_ordering_settings').upsert({id:1,enabled,updated_at:new Date().toISOString(),updated_by:user.id});if(error)return J({error:error.message},500);return J({ok:true,enabled})}
if(action==='stock_list'){if(!admin&&!staff)return J({error:'Staff access required'},403);const {data,error}=await db.from('loyalty_menu_categories').select('id,name,sort_order,loyalty_menu_items(id,name,price_text,description,sort_order,active,in_stock)').eq('active',true).order('sort_order',{ascending:true});if(error)return J({error:error.message},500);const categories=(data||[]).map((c:any)=>({...c,loyalty_menu_items:(c.loyalty_menu_items||[]).filter((i:any)=>i.active).sort((a:any,b:any)=>(a.sort_order-b.sort_order)||a.name.localeCompare(b.name))}));return J({categories})}
if(action==='set_stock'){if(!admin&&!staff)return J({error:'Staff access required'},403);const id=String(b.id||'');if(!id)return J({error:'Item required'},400);const inStock=!!b.in_stock;const {data,error}=await db.from('loyalty_menu_items').update({in_stock:inStock,updated_at:new Date().toISOString()}).eq('id',id).eq('active',true).select('id,name,in_stock').single();if(error)return J({error:error.message},500);return J({ok:true,item:data})}
if(action==='create'){const {data:s}=await db.from('collection_ordering_settings').select('enabled').eq('id',1).single();if(!s?.enabled)return J({error:'Collection ordering is currently closed.'},409);const requested=Array.isArray(b.items)?b.items:[];if(!requested.length)return J({error:'Add at least one item.'},400);const ids=[...new Set(requested.map((x:any)=>String(x?.id||'')).filter(Boolean))].slice(0,40);if(!ids.length)return J({error:'Please refresh the menu and select your items again.'},400);const {data:menu,error:me}=await db.from('loyalty_menu_items').select('id,name,category_id,price_text,description,active,in_stock').in('id',ids);if(me)return J({error:me.message},500);const byId=new Map((menu||[]).map((i:any)=>[i.id,i]));
const categoryIds=[...new Set((menu||[]).map((i:any)=>i.category_id).filter(Boolean))];let categoryRows:any[]=[];if(categoryIds.length){const {data,error}=await db.from('loyalty_menu_categories').select('id,name').in('id',categoryIds);if(error)return J({error:'Could not load menu categories. Please try again.'},500);categoryRows=data||[]}const categoryById=new Map(categoryRows.map((c:any)=>[c.id,c.name]));
const {data:groups,error:ge}=await db.from('loyalty_modifier_test_groups').select('id,menu_item_id,name,selection_type,required,min_select,max_select,sort_order,active').in('menu_item_id',ids).eq('active',true);if(ge)return J({error:'Could not validate menu choices.'},500);const groupIds=(groups||[]).map((g:any)=>g.id);let opts:any[]=[];if(groupIds.length){const {data,error}=await db.from('loyalty_modifier_test_options').select('id,group_id,name,price_delta,sort_order,active').in('group_id',groupIds).eq('active',true);if(error)return J({error:'Could not validate menu choices.'},500);opts=data||[]}
const groupsByItem=new Map<string,any[]>();for(const g of(groups||[])){const a=groupsByItem.get(g.menu_item_id)||[];a.push(g);groupsByItem.set(g.menu_item_id,a)}const optsByGroup=new Map<string,any[]>();for(const o of opts){const a=optsByGroup.get(o.group_id)||[];a.push(o);optsByGroup.set(o.group_id,a)}
const unavailable:string[]=[];const clean:any[]=[];for(const x of requested.slice(0,40)){const id=String(x?.id||''),m:any=byId.get(id);if(!m||!m.active||!m.in_stock){unavailable.push(m?.name||String(x?.name||'Item'));continue}const itemGroups=(groupsByItem.get(id)||[]).sort((a:any,b:any)=>a.sort_order-b.sort_order);const reqMods=Array.isArray(x?.modifiers)?x.modifiers:[];const selectedByGroup=new Map<string,string[]>();for(const rm of reqMods){const gid=String(rm?.group_id||'');const ids2=Array.isArray(rm?.option_ids)?rm.option_ids.map((z:any)=>String(z)):[];if(gid)selectedByGroup.set(gid,ids2)}const modifierSummary:string[]=[];let modifierTotal=0;for(const g of itemGroups){const allowedOptions=(optsByGroup.get(g.id)||[]).sort((a:any,b:any)=>a.sort_order-b.sort_order);const allowedMap=new Map(allowedOptions.map((o:any)=>[o.id,o]));const chosenRaw=selectedByGroup.get(g.id)||[];const chosen=[...new Set(chosenRaw)].map((oid:any)=>allowedMap.get(oid)).filter(Boolean);const min=Math.max(0,Number(g.min_select)||0),max=g.max_select==null?999:Math.max(0,Number(g.max_select)||0);if((g.required||min>0)&&chosen.length<Math.max(1,min))return J({error:`Please choose ${g.name} for ${m.name}.`},400);if(chosen.length>max)return J({error:`Too many choices selected for ${g.name}.`},400);if(g.selection_type==='single'&&chosen.length>1)return J({error:`Choose only one option for ${g.name}.`},400);if(chosen.length){const names=chosen.map((o:any)=>o.name);modifierSummary.push(`${g.name}: ${names.join(', ')}`);modifierTotal+=chosen.reduce((n:number,o:any)=>n+gbp(o.price_delta),0)}}
const allowed=ingredientList(m.description);const wanted=Array.isArray(x?.removed)?x.removed.map((v:any)=>String(v).trim()).filter(Boolean).slice(0,14):[];const removed:string[]=[];for(const w of wanted){const match=allowed.find((a:any)=>String(a).toLowerCase()===w.toLowerCase());if(match&&!removed.some(r=>r.toLowerCase()===String(match).toLowerCase()))removed.push(String(match))}const categoryName=String(categoryById.get(m.category_id)||'').trim();const itemLabel=categoryName?`${categoryName} — ${m.name}`:m.name;const displayName=modifierSummary.length?`${itemLabel} — ${modifierSummary.join(' · ')}`:itemLabel;clean.push({id:m.id,base_name:m.name,category_id:m.category_id||null,category_name:categoryName,name:displayName,price:m.price_text,qty:Math.max(1,Math.min(20,Number(x?.qty)||1)),removed,modifiers:modifierSummary,modifier_total:Number(modifierTotal.toFixed(2))})}
if(unavailable.length)return J({error:`Out of stock: ${[...new Set(unavailable)].join(', ')}. Please remove ${unavailable.length===1?'it':'them'} and try again.`,out_of_stock:[...new Set(unavailable)]},409);if(!clean.length)return J({error:'Add at least one available item.'},400);const customerName=String(b.customer_name||profile?.full_name||'').trim().slice(0,120),customerPhone=cleanPhone(b.customer_phone||profile?.phone||'');if(!customerName)return J({error:'Full name is required before placing the order.'},400);if(customerPhone.replace(/\D/g,'').length<7)return J({error:'A valid phone number is required before placing the order.'},400);const {data:o,error}=await db.from('collection_orders').insert({customer_id:user.id,customer_name:customerName,customer_phone:customerPhone,items:clean,order_notes:String(b.order_notes||'').slice(0,500)||null,collection_time:String(b.collection_time||'ASAP').slice(0,80),status:'pending'}).select('*').single();if(error)return J({error:error.message},500);return J({ok:true,order:o})}
if(action==='my_orders'){const {data,error}=await db.from('collection_orders').select('*').eq('customer_id',user.id).order('created_at',{ascending:false}).limit(20);if(error)return J({error:error.message},500);return J({orders:data||[]})}
if(action==='kds_orders'){if(!admin&&!staff)return J({error:'Staff access required'},403);const {data,error}=await db.from('collection_orders').select('*').in('status',['pending','accepted','preparing','ready']).order('created_at',{ascending:true});if(error)return J({error:error.message},500);return J({orders:data||[],rejection_reasons:REASONS})}
if(['accept','preparing','ready','collected','reject'].includes(action)){if(!admin&&!staff)return J({error:'Staff access required'},403);const id=String(b.id||'');const {data:o}=await db.from('collection_orders').select('*').eq('id',id).single();if(!o)return J({error:'Order not found'},404);let patch:any={updated_at:new Date().toISOString(),handled_by:user.id};if(action==='accept'){if(o.status!=='pending')return J({error:'Order is no longer awaiting a decision.'},409);patch.status='accepted';patch.accepted_at=new Date().toISOString();patch.rejection_reason=null}else if(action==='reject'){if(o.status!=='pending')return J({error:'Order is no longer awaiting a decision.'},409);const reason=String(b.reason||'').trim();if(!REASONS.includes(reason))return J({error:'Select a rejection reason.'},400);patch.status='rejected';patch.rejected_at=new Date().toISOString();patch.rejection_reason=reason}else if(action==='preparing'){if(!['accepted','preparing'].includes(o.status))return J({error:'Accept the order first.'},409);patch.status='preparing'}else if(action==='ready'){if(!['accepted','preparing','ready'].includes(o.status))return J({error:'Order cannot be marked ready.'},409);patch.status='ready';patch.ready_at=new Date().toISOString()}else if(action==='collected'){if(o.status!=='ready')return J({error:'Order must be ready first.'},409);patch.status='collected';patch.collected_at=new Date().toISOString()}const {data,error}=await db.from('collection_orders').update(patch).eq('id',id).select('*').single();if(error)return J({error:error.message},500);return J({ok:true,order:data})}return J({error:'Unknown action'},400)});

