(function(){
'use strict';
const U='https://bpnkouymdvcogeaqjmxl.supabase.co';
const K='sb_publishable_v6rJbF4IfGZTKtbuQtmsmQ_lS3sXWFa';
const DEALS=[
 {category:'Chicken Tenders',title:'Winter Tenders',description:'4 Chicken Tenders + Chips + Can',normal:'£13.50',price:'£12.50',icon:'❄️'},
 {category:'Dexter’s Smash Burgers',title:'Valentine Burger Deal',description:'2 Dexter Smash Burgers + 2 Cans',normal:'£20.40',price:'£18.99',icon:'❤️'},
 {category:'Dexter’s Street Subs',title:'Street Sub Meal',description:'Chicken Mayo Melt + Chips + Can',normal:'£11.50',price:'£10.75',icon:'🍀'},
 {category:'Chicken Burgers',title:'Easter Chicken Deal',description:'Classic Chicken Smash + Can + Garlic Bread',normal:'£14.20',price:'£13.25',icon:'🐣'},
 {category:'Dexter’s Smash Burgers',title:'Smash & Rings',description:'Dexter Smash + Can + Onion Rings',normal:'£14.70',price:'£13.49',icon:'☀️'},
 {category:'Dexter’s Street Subs',title:'Summer Sub',description:'Southern Fried Chicken Sub + Chips + Can',normal:'£12.00',price:'£10.99',icon:'🌤️'},
 {category:'Chicken Tenders',title:'Summer Tenders',description:'6 Chicken Tenders + Chips + Can',normal:'£15.50',price:'£14.25',icon:'☀️'},
 {category:'Chicken Tenders',title:'BBQ Summer',description:'BBQ Tenders + Chips + Can',normal:'£13.50',price:'£12.50',icon:'🍔'},
 {category:'Dexter’s Street Subs',title:'Back to Routine',description:'Chicken Mayo Melt + Chips + Can',normal:'£11.50',price:'£10.75',icon:'🔥'},
 {category:'Inferno Chicken Tenders',title:'Halloween Inferno',description:'Inferno Chicken + Chips + Can',normal:'£14.00',price:'£12.99',icon:'🎃'},
 {category:'Dexter’s Rice Bowls',title:'Winter Warmer',description:'Chicken Curry Rice Bowl + Can',normal:'£11.00',price:'£10.25',icon:'🍟'},
 {category:'Dexter’s Smash Burgers',title:'Christmas Burger Feast',description:'2 Dexter Smash Burgers + 2 Cans + Onion Rings',normal:'£24.90',price:'£22.99',icon:'🎄'}
];
let customerClaim=null,claimTimer=null,scanStream=null,scanFrame=null,busy=false;
function session(){try{const j=JSON.parse(localStorage.getItem('sb-bpnkouymdvcogeaqjmxl-auth-token')||'null');return j?.currentSession||j?.session||j||null}catch(e){return null}}
function token(){return session()?.access_token||null}
async function api(path,opt){const t=token();if(!t)throw new Error('Sign in required');const r=await fetch(U+path,Object.assign({},opt||{},{headers:Object.assign({apikey:K,Authorization:'Bearer '+t,'Content-Type':'application/json'},(opt&&opt.headers)||{})}));const text=await r.text();let d=null;try{d=text?JSON.parse(text):null}catch(e){}if(!r.ok)throw new Error((d&&(d.message||d.error_description||d.error))||('Request failed '+r.status));return d}
async function rpc(name,body){return api('/rest/v1/rpc/'+name,{method:'POST',body:JSON.stringify(body||{})})}
function deal(){return DEALS[new Date().getMonth()]}
function dealKey(d){const n=new Date(),m=n.getMonth()+1;return 'yearly-'+n.getFullYear()+'-'+String(m).padStart(2,'0')+'-'+d.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function nextMonthIso(){const n=new Date();return new Date(n.getFullYear(),n.getMonth()+1,1,0,0,0,0).toISOString()}
function css(){if(document.getElementById('dextersDealsLiveStyle'))return;const s=document.createElement('style');s.id='dextersDealsLiveStyle';s.textContent='.ddl-cat{display:inline-block;background:#243a5e;color:#ffd43b;border-radius:999px;padding:5px 9px;font-size:12px;font-weight:900;text-transform:uppercase}.ddl-price{font-size:28px;font-weight:950;color:#9ff3c5}.ddl-old{text-decoration:line-through;color:#94a3b8;margin-right:8px}.ddl-qr{background:#fff;border-radius:14px;padding:10px;width:max-content;max-width:100%;margin:12px auto}.ddl-note{font-size:12px;color:#b8c4d6}.ddl-status{font-weight:900}.ddl-good{color:#9ff3c5}.ddl-bad{color:#ffb4b4}.ddl-switch{position:relative;width:58px;height:32px;display:inline-block;flex:none}.ddl-switch input{opacity:0;width:0;height:0}.ddl-slider{position:absolute;inset:0;background:#3a4658;border-radius:999px;cursor:pointer}.ddl-slider:before{content:"";position:absolute;width:24px;height:24px;left:4px;top:4px;background:#fff;border-radius:50%;transition:.2s}.ddl-switch input:checked+.ddl-slider{background:#22c55e}.ddl-switch input:checked+.ddl-slider:before{transform:translateX(26px)}#dextersDealsStaffCard .ddl-row{display:flex;align-items:center;justify-content:space-between;gap:14px}#dextersDealScanModal{position:fixed;inset:0;background:#000d;z-index:9999;display:none;align-items:flex-end;justify-content:center}#dextersDealScanModal.ddl-open{display:flex}#dextersDealScanModal .ddl-sheet{width:min(700px,100%);max-height:92vh;overflow:auto;background:#132038;border-radius:22px 22px 0 0;padding:18px;box-sizing:border-box}#dextersDealScanModal video{width:100%;max-height:50vh;background:#000;border-radius:14px}#dextersDealScanModal input{width:100%;box-sizing:border-box;border:1px solid #ffffff30;border-radius:10px;padding:12px;background:#081422;color:#fff;margin:8px 0}';document.head.appendChild(s)}
function drawQr(el,text){el.innerHTML='';try{if(window.QRCode){new window.QRCode(el,{text,width:190,height:190});return}}catch(e){}el.innerHTML='<div style="color:#111;padding:10px;font-weight:900;word-break:break-all">'+text+'</div>'}
async function autoEnabled(){try{const d=await api('/rest/v1/loyalty_deal_settings?id=eq.1&select=auto_enabled',{method:'GET'});return !!(Array.isArray(d)&&d[0]&&d[0].auto_enabled)}catch(e){return false}}
function removeCustomerDeal(){const x=document.getElementById('dextersDealsCustomerOffer');if(x)x.remove();customerClaim=null;if(claimTimer){clearInterval(claimTimer);claimTimer=null}}
async function ensureCustomerDeal(){if(busy||!token())return;const offers=document.getElementById('offers');if(!offers)return;busy=true;try{if(!(await autoEnabled())){removeCustomerDeal();return}const d=deal();const x=await rpc('loyalty_claim_deal',{p_deal_key:dealKey(d),p_expires_at:nextMonthIso()});const claim=Array.isArray(x)?x[0]:x;if(!claim||claim.redeemed_at){removeCustomerDeal();return}customerClaim=claim;let box=document.getElementById('dextersDealsCustomerOffer');if(!box){box=document.createElement('div');box.id='dextersDealsCustomerOffer';box.className='offer';offers.prepend(box)}box.innerHTML='<div class="ddl-cat">'+d.category+'</div><h3 style="margin:10px 0 6px">'+d.icon+' '+d.title+'</h3><p>'+d.description+'</p><div><span class="ddl-old">'+d.normal+'</span><span class="ddl-price">'+d.price+'</span></div><p class="ddl-status ddl-good">ONE USE ONLY</p><div id="dextersDealsCustomerQr" class="ddl-qr"></div><p class="ddl-note">Show this QR to staff. Once staff scan it successfully, this deal disappears from your account and cannot be used again.</p><p class="ddl-note">Paid modifiers such as Add Cheese and sauces are charged on top.</p>';drawQr(document.getElementById('dextersDealsCustomerQr'),'DEXTERS_DEAL:'+claim.claim_id);if(!claimTimer)claimTimer=setInterval(checkClaim,1500)}catch(e){}finally{busy=false}}
async function checkClaim(){if(!customerClaim||!token())return;try{const d=await api('/rest/v1/loyalty_deal_claims?id=eq.'+encodeURIComponent(customerClaim.claim_id)+'&select=redeemed_at',{method:'GET'});if(Array.isArray(d)&&d[0]&&d[0].redeemed_at)removeCustomerDeal()}catch(e){}}
async function ensureStaff(){const page=document.getElementById('staffPage');if(!page||document.getElementById('dextersDealsStaffCard')||!token())return;const card=document.createElement('div');card.className='card';card.id='dextersDealsStaffCard';card.innerHTML='<h2>🔥 Dexter\'s Deals</h2><div class="ddl-row"><div><b>Automatic Deals</b><div id="dextersDealsAutoStatus" class="ddl-status">Checking…</div><p class="ddl-note">OFF pauses the monthly deal for all customers. ON resumes it.</p></div><label class="ddl-switch"><input id="dextersDealsAutoToggle" type="checkbox"><span class="ddl-slider"></span></label></div><button type="button" class="btn" id="dextersDealScanBtn">Scan Customer Deal QR</button><div id="dextersDealsStaffResult" class="ddl-note" style="margin-top:10px"></div>';page.appendChild(card);const toggle=card.querySelector('#dextersDealsAutoToggle'),status=card.querySelector('#dextersDealsAutoStatus');const on=await autoEnabled();toggle.checked=on;status.textContent=on?'ON — monthly deals active':'OFF — automatic deals paused';status.className='ddl-status '+(on?'ddl-good':'ddl-bad');toggle.onchange=async()=>{toggle.disabled=true;try{const r=await rpc('loyalty_set_auto_deals',{p_enabled:toggle.checked});const v=!!(r&&r.auto_enabled);toggle.checked=v;status.textContent=v?'ON — monthly deals active':'OFF — automatic deals paused';status.className='ddl-status '+(v?'ddl-good':'ddl-bad');if(v)ensureCustomerDeal();else removeCustomerDeal()}catch(e){toggle.checked=!toggle.checked;status.textContent='Could not change deals: '+e.message;status.className='ddl-status ddl-bad'}finally{toggle.disabled=false}};card.querySelector('#dextersDealScanBtn').onclick=openScanner}
function ensureScanner(){if(document.getElementById('dextersDealScanModal'))return;const m=document.createElement('div');m.id='dextersDealScanModal';m.innerHTML='<div class="ddl-sheet"><div style="display:flex;justify-content:space-between;align-items:center"><h2 style="margin:0">Scan Deal QR</h2><button type="button" class="btn" id="ddlCloseScan">Close</button></div><p class="ddl-note">Point the camera at the customer\'s Dexter\'s Deal QR.</p><video id="ddlScanVideo" playsinline muted></video><canvas id="ddlScanCanvas" style="display:none"></canvas><div id="ddlScanStatus" class="ddl-status" style="margin:10px 0">Ready.</div><input id="ddlManualCode" placeholder="DEXTERS_DEAL:claim-id"><button type="button" class="btn" id="ddlManualRedeem">Redeem code</button></div>';document.body.appendChild(m);m.querySelector('#ddlCloseScan').onclick=closeScanner;m.querySelector('#ddlManualRedeem').onclick=()=>redeem(m.querySelector('#ddlManualCode').value)}
async function loadJsQr(){if(window.jsQR)return;await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.js';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
async function openScanner(){ensureScanner();const m=document.getElementById('dextersDealScanModal'),st=document.getElementById('ddlScanStatus'),v=document.getElementById('ddlScanVideo');m.classList.add('ddl-open');st.textContent='Starting camera…';try{scanStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});v.srcObject=scanStream;await v.play();await loadJsQr().catch(()=>{});st.textContent='Scanning…';scanLoop()}catch(e){st.textContent='Camera unavailable. Use the code box below.';st.className='ddl-status ddl-bad'}}
function closeScanner(){if(scanFrame)cancelAnimationFrame(scanFrame);scanFrame=null;if(scanStream){scanStream.getTracks().forEach(t=>t.stop());scanStream=null}document.getElementById('dextersDealScanModal')?.classList.remove('ddl-open')}
function scanLoop(){const v=document.getElementById('ddlScanVideo'),c=document.getElementById('ddlScanCanvas');if(!v||!c||!scanStream)return;const ctx=c.getContext('2d',{willReadFrequently:true});if(v.readyState>=2&&v.videoWidth){c.width=v.videoWidth;c.height=v.videoHeight;ctx.drawImage(v,0,0,c.width,c.height);try{const im=ctx.getImageData(0,0,c.width,c.height);if(window.jsQR){const q=window.jsQR(im.data,c.width,c.height,{inversionAttempts:'dontInvert'});if(q&&q.data){redeem(q.data);return}}}catch(e){}}scanFrame=requestAnimationFrame(scanLoop)}
async function redeem(raw){const st=document.getElementById('ddlScanStatus');const m=String(raw||'').trim().match(/^DEXTERS_DEAL:([0-9a-f-]{36})$/i);if(!m){st.textContent='Invalid Dexter’s Deal QR.';st.className='ddl-status ddl-bad';return}if(scanFrame)cancelAnimationFrame(scanFrame);scanFrame=null;st.textContent='Redeeming…';try{const r=await rpc('loyalty_redeem_deal',{p_claim_id:m[1]});if(r&&r.ok){st.textContent='REDEEMED ✓ '+(r.customer_name||'Customer');st.className='ddl-status ddl-good';const out=document.getElementById('dextersDealsStaffResult');if(out){out.textContent='Last redemption: '+(r.customer_name||'Customer')+' — success';out.className='ddl-status ddl-good'}if(scanStream){scanStream.getTracks().forEach(t=>t.stop());scanStream=null}}else{st.textContent=r&&r.status==='already_redeemed'?'BLOCKED — deal already redeemed.':'BLOCKED — deal unavailable.';st.className='ddl-status ddl-bad'}}catch(e){st.textContent='Could not redeem: '+e.message;st.className='ddl-status ddl-bad'}}
function boot(){css();ensureScanner();ensureCustomerDeal();ensureStaff()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();setTimeout(boot,500);setTimeout(boot,1500);setInterval(boot,10000);new MutationObserver(()=>setTimeout(boot,0)).observe(document.body,{childList:true,subtree:true});
})();
