(function(){
'use strict';
const U='https://bpnkouymdvcogeaqjmxl.supabase.co';
const K='sb_publishable_v6rJbF4IfGZTKtbuQtmsmQ_lS3sXWFa';
const DEALS=[
 {category:'Chicken Tenders',title:'Winter Tenders',description:'4 Chicken Tenders + Chips + Can',normal:'£13.50',price:'£12.50',icon:'❄️'},
 {category:'Dexter’s Smash Burgers',title:'Valentine Burger Deal',description:'2 Dexter Smash Burgers + 2 Cans',normal:'£20.40',price:'£18.99',icon:'❤️'},
 {category:'Dexter’s Street Subs',title:'Street Sub Meal',description:'Chicken Mayo Melt + Chips + Can',normal:'£11.50',price:'£10.75',icon:'🍀'},
 {category:'Chicken Burgers',title:'Easter Chicken Deal',description:'Classic Chicken Smash + Can + Garlic Bread',normal:'£14.20',price:'£13.25',icon:'🐣'},
 {category:'Dexter’s Smash Burgers',title:'Smash & Rings',description:'Dexter Smash + Can + Onion Rings',normal:'£14.70',price:'£13.49',icon:'☀️'},
 {category:'Dexter’s Street Subs',title:'Summer Sub',description:'Southern Fried Chicken Sub + Chips + Can',normal:'£12.00',price:'£10.99',icon:'🌤️'},
 {category:'Chicken Tenders',title:'Summer Tenders',description:'6 Chicken Tenders + Chips + Can',normal:'£15.50',price:'£14.25',icon:'☀️'},
 {category:'Chicken Tenders',title:'BBQ Summer',description:'BBQ Tenders + Chips + Can',normal:'£13.50',price:'£12.50',icon:'🍔'},
 {category:'Dexter’s Street Subs',title:'Back to Routine',description:'Chicken Mayo Melt + Chips + Can',normal:'£11.50',price:'£10.75',icon:'🔥'},
 {category:'Inferno Chicken Tenders',title:'Halloween Inferno',description:'Inferno Chicken + Chips + Can',normal:'£14.00',price:'£12.99',icon:'🎃'},
 {category:'Dexter’s Rice Bowls',title:'Winter Warmer',description:'Chicken Curry Rice Bowl + Can',normal:'£11.00',price:'£10.25',icon:'🍟'},
 {category:'Dexter’s Smash Burgers',title:'Christmas Burger Feast',description:'2 Dexter Smash Burgers + 2 Cans + Onion Rings',normal:'£24.90',price:'£22.99',icon:'🎄'}
];
let customerClaim=null,customerTimer=null,scanStream=null,scanTimer=null;
function token(){try{const raw=localStorage.getItem('sb-bpnkouymdvcogeaqjmxl-auth-token');if(!raw)return null;const j=JSON.parse(raw);return j.access_token||(j.currentSession&&j.currentSession.access_token)||(j.session&&j.session.access_token)||null}catch(e){return null}}
async function api(path,opt){const t=token();if(!t)throw new Error('Sign in required');const r=await fetch(U+path,Object.assign({},opt||{},{headers:Object.assign({apikey:K,Authorization:'Bearer '+t,'Content-Type':'application/json'},(opt&&opt.headers)||{})}));let d=null;try{d=await r.json()}catch(e){}if(!r.ok)throw new Error((d&&(d.message||d.error_description||d.error))||'Request failed');return d}
async function rpc(name,body){return api('/rest/v1/rpc/'+name,{method:'POST',body:JSON.stringify(body||{})})}
function dealKey(d){const now=new Date(),m=now.getMonth()+1;return 'yearly-'+now.getFullYear()+'-'+String(m).padStart(2,'0')+'-'+d.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function nextMonthIso(){const n=new Date(),x=new Date(n.getFullYear(),n.getMonth()+1,1,0,0,0,0);return x.toISOString()}
function css(){if(document.getElementById('dextersDealsLiveStyle'))return;const s=document.createElement('style');s.id='dextersDealsLiveStyle';s.textContent=`#dextersDealsLiveCard .ddl-cat{display:inline-block;background:#243a5e;color:#ffd43b;border-radius:999px;padding:5px 9px;font-size:12px;font-weight:900;text-transform:uppercase;letter-spacing:.04em}#dextersDealsLiveCard .ddl-price{font-size:28px;font-weight:950;color:#9ff3c5}#dextersDealsLiveCard .ddl-old{text-decoration:line-through;color:#94a3b8;margin-right:8px}#dextersDealsLiveCard .ddl-qr-wrap{background:#fff;border-radius:14px;padding:10px;width:max-content;max-width:100%;margin:12px auto}#dextersDealsLiveCard canvas{display:block;max-width:100%;height:auto}.ddl-note{font-size:12px;color:#b8c4d6}.ddl-status{font-weight:900}.ddl-good{color:#9ff3c5}.ddl-bad{color:#ffb4b4}.ddl-switch{position:relative;width:58px;height:32px;display:inline-block;flex:none}.ddl-switch input{opacity:0;width:0;height:0}.ddl-slider{position:absolute;inset:0;background:#3a4658;border-radius:999px;cursor:pointer}.ddl-slider:before{content:'';position:absolute;width:24px;height:24px;left:4px;top:4px;background:#fff;border-radius:50%;transition:.2s}.ddl-switch input:checked+.ddl-slider{background:#22c55e}.ddl-switch input:checked+.ddl-slider:before{transform:translateX(26px)}#dextersDealsStaffCard .ddl-row{display:flex;align-items:center;justify-content:space-between;gap:14px}#dextersDealScanModal{position:fixed;inset:0;background:#000d;z-index:9999;display:none;align-items:flex-end;justify-content:center}#dextersDealScanModal.ddl-open{display:flex}#dextersDealScanModal .ddl-sheet{width:min(700px,100%);max-height:92vh;overflow:auto;background:#132038;border-radius:22px 22px 0 0;padding:18px;box-sizing:border-box}#dextersDealScanModal video{width:100%;max-height:50vh;background:#000;border-radius:14px}#dextersDealScanModal input{width:100%;box-sizing:border-box;border:1px solid #ffffff30;border-radius:10px;padding:12px;background:#081422;color:#fff;margin:8px 0}.ddl-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.ddl-actions button{width:100%}`;document.head.appendChild(s)}
function loadScript(id,src){return new Promise((res,rej)=>{if(document.getElementById(id))return res();const s=document.createElement('script');s.id=id;s.src=src;s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
async function autoEnabled(){try{const d=await api('/rest/v1/loyalty_deal_settings?id=eq.1&select=auto_enabled',{method:'GET'});return !!(Array.isArray(d)&&d[0]&&d[0].auto_enabled)}catch(e){return false}}
async function ensureCustomerCard(){const home=document.getElementById('homePage');if(!home||document.getElementById('dextersDealsLiveCard'))return;const t=token();if(!t)return;const on=await autoEnabled();if(!on)return;const d=DEALS[new Date().getMonth()];let claim;try{const x=await rpc('loyalty_claim_deal',{p_deal_key:dealKey(d),p_expires_at:nextMonthIso()});claim=Array.isArray(x)?x[0]:x}catch(e){return}if(!claim||claim.redeemed_at)return;customerClaim=claim;const card=document.createElement('div');card.className='card';card.id='dextersDealsLiveCard';card.innerHTML=`<h2>${d.icon} Dexter's Deals</h2><div class="ddl-cat"></div><h3 class="ddl-title"></h3><p class="ddl-desc"></p><div><span class="ddl-old"></span><span class="ddl-price"></span></div><p class="ddl-status ddl-good">ONE USE ONLY</p><div class="ddl-qr-wrap"><canvas id="dextersDealQr"></canvas></div><p class="ddl-note">Show this QR to staff when using the deal. Once staff scan it, this deal disappears from your account and cannot be used again.</p><p class="ddl-note">Paid modifiers such as Add Cheese and sauces are charged on top.</p>`;card.querySelector('.ddl-cat').textContent=d.category;card.querySelector('.ddl-title').textContent=d.title;card.querySelector('.ddl-desc').textContent=d.description;card.querySelector('.ddl-old').textContent=d.normal;card.querySelector('.ddl-price').textContent=d.price;home.appendChild(card);try{await loadScript('dextersQRCodeLib','https://cdn.jsdelivr.net/npm/qrcode@1.5.4/build/qrcode.min.js');if(window.QRCode&&QRCode.toCanvas)QRCode.toCanvas(document.getElementById('dextersDealQr'),'DEXTERS_DEAL:'+claim.claim_id,{width:220,margin:1})}catch(e){const q=document.querySelector('#dextersDealsLiveCard .ddl-qr-wrap');if(q)q.innerHTML='<div style="color:#111;padding:10px;font-weight:900">Deal code: '+String(claim.claim_id)+'</div>'}if(customerTimer)clearInterval(customerTimer);customerTimer=setInterval(checkCustomerClaim,1500)}
async function checkCustomerClaim(){if(!customerClaim)return;try{const d=await api('/rest/v1/loyalty_deal_claims?id=eq.'+encodeURIComponent(customerClaim.claim_id)+'&select=redeemed_at',{method:'GET'});if(Array.isArray(d)&&d[0]&&d[0].redeemed_at){if(customerTimer)clearInterval(customerTimer);customerClaim=null;const c=document.getElementById('dextersDealsLiveCard');if(c)c.remove()}}catch(e){}}
async function ensureStaffCard(){const page=document.getElementById('staffPage');if(!page||document.getElementById('dextersDealsStaffCard'))return;const t=token();if(!t)return;const card=document.createElement('div');card.className='card';card.id='dextersDealsStaffCard';card.innerHTML=`<h2>🔥 Dexter's Deals</h2><div class="ddl-row"><div><b>Automatic Deals</b><div id="dextersDealsAutoStatus" class="ddl-status">Checking…</div><p class="ddl-note">OFF pauses the monthly deal for all customers. ON resumes it.</p></div><label class="ddl-switch"><input id="dextersDealsAutoToggle" type="checkbox"><span class="ddl-slider"></span></label></div><button type="button" class="btn" id="dextersDealScanBtn">Scan Customer Deal QR</button><div id="dextersDealsStaffResult" class="ddl-note" style="margin-top:10px"></div>`;page.appendChild(card);const toggle=card.querySelector('#dextersDealsAutoToggle'),status=card.querySelector('#dextersDealsAutoStatus');const on=await autoEnabled();toggle.checked=on;status.textContent=on?'ON — monthly deals active':'OFF — automatic deals paused';status.className='ddl-status '+(on?'ddl-good':'ddl-bad');toggle.onchange=async()=>{toggle.disabled=true;try{const r=await rpc('loyalty_set_auto_deals',{p_enabled:toggle.checked});const v=!!(r&&r.auto_enabled);toggle.checked=v;status.textContent=v?'ON — monthly deals active':'OFF — automatic deals paused';status.className='ddl-status '+(v?'ddl-good':'ddl-bad')}catch(e){toggle.checked=!toggle.checked;status.textContent='Could not change deals: '+e.message;status.className='ddl-status ddl-bad'}finally{toggle.disabled=false}};card.querySelector('#dextersDealScanBtn').onclick=openScanner}
function ensureScanner(){if(document.getElementById('dextersDealScanModal'))return;const m=document.createElement('div');m.id='dextersDealScanModal';m.innerHTML=`<div class="ddl-sheet"><div class="ddl-row" style="display:flex;justify-content:space-between;align-items:center"><h2 style="margin:0">Scan Deal QR</h2><button type="button" class="btn" id="ddlCloseScan">Close</button></div><p class="ddl-note">Point the camera at the customer's Dexter's Deal QR.</p><video id="ddlScanVideo" playsinline muted></video><canvas id="ddlScanCanvas" style="display:none"></canvas><div id="ddlScanStatus" class="ddl-status" style="margin:10px 0">Ready.</div><p class="ddl-note">Camera fallback: paste/type the code shown under the customer's QR.</p><input id="ddlManualCode" placeholder="DEXTERS_DEAL:claim-id"><button type="button" class="btn" id="ddlManualRedeem">Redeem code</button></div>`;document.body.appendChild(m);m.querySelector('#ddlCloseScan').onclick=closeScanner;m.querySelector('#ddlManualRedeem').onclick=()=>redeemCode(m.querySelector('#ddlManualCode').value)}
async function openScanner(){ensureScanner();const m=document.getElementById('dextersDealScanModal'),st=document.getElementById('ddlScanStatus'),v=document.getElementById('ddlScanVideo');m.classList.add('ddl-open');st.textContent='Starting camera…';st.className='ddl-status';try{scanStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});v.srcObject=scanStream;await v.play();st.textContent='Scanning…';try{await loadScript('dextersJsQrLib','https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.js')}catch(e){}scanLoop()}catch(e){st.textContent='Camera unavailable. Use the code box below.';st.className='ddl-status ddl-bad'}}
function closeScanner(){if(scanTimer)cancelAnimationFrame(scanTimer);scanTimer=null;if(scanStream){scanStream.getTracks().forEach(t=>t.stop());scanStream=null}const m=document.getElementById('dextersDealScanModal');if(m)m.classList.remove('ddl-open')}
function scanLoop(){const v=document.getElementById('ddlScanVideo'),c=document.getElementById('ddlScanCanvas');if(!v||!c||!scanStream)return;const ctx=c.getContext('2d',{willReadFrequently:true});if(v.readyState>=2&&v.videoWidth){const w=v.videoWidth,h=v.videoHeight;c.width=w;c.height=h;ctx.drawImage(v,0,0,w,h);try{const img=ctx.getImageData(0,0,w,h);if(window.jsQR){const qr=jsQR(img.data,w,h,{inversionAttempts:'dontInvert'});if(qr&&qr.data){redeemCode(qr.data);return}}}catch(e){}}scanTimer=requestAnimationFrame(scanLoop)}
async function redeemCode(raw){const st=document.getElementById('ddlScanStatus');if(!st)return;const s=String(raw||'').trim(),m=s.match(/^DEXTERS_DEAL:([0-9a-f-]{36})$/i);if(!m){st.textContent='Invalid Dexter’s Deal QR.';st.className='ddl-status ddl-bad';return}if(scanTimer)cancelAnimationFrame(scanTimer);scanTimer=null;st.textContent='Redeeming…';st.className='ddl-status';try{const r=await rpc('loyalty_redeem_deal',{p_claim_id:m[1]});if(r&&r.ok){st.textContent='REDEEMED ✓ '+(r.customer_name||'Customer')+' — '+String(r.deal_key||'').replace(/^yearly-\d{4}-\d{2}-/,'').replace(/-/g,' ');st.className='ddl-status ddl-good';const result=document.getElementById('dextersDealsStaffResult');if(result){result.textContent='Last redemption: '+(r.customer_name||'Customer')+' — success';result.className='ddl-status ddl-good'}if(scanStream){scanStream.getTracks().forEach(t=>t.stop());scanStream=null}}else{const status=r&&r.status;st.textContent=status==='already_redeemed'?'BLOCKED — deal already redeemed.':status==='expired'?'BLOCKED — deal expired.':'BLOCKED — invalid deal QR.';st.className='ddl-status ddl-bad'}}catch(e){st.textContent='Could not redeem: '+e.message;st.className='ddl-status ddl-bad'}}
function boot(){css();ensureScanner();ensureCustomerCard();ensureStaffCard()}
boot();setTimeout(boot,400);setTimeout(boot,1500);new MutationObserver(()=>setTimeout(boot,0)).observe(document.body,{childList:true,subtree:true});setInterval(()=>{ensureCustomerCard();ensureStaffCard()},10000);
})();
