(function(){
const U='https://bpnkouymdvcogeaqjmxl.supabase.co',K='sb_publishable_v6rJbF4IfGZTKtbuQtmsmQ_lS3sXWFa',V='BKFP4y8dn01iosiV_LvFfeSA7O5ssNzSmQpL0Umhe2grStiT4yiGkSRhY_yuL-8AXrq-oTeBa0scgKfEdS4nJAE';
function token(){try{const x=JSON.parse(localStorage.getItem('sb-bpnkouymdvcogeaqjmxl-auth-token')||'null');return x?.access_token||x?.currentSession?.access_token||x?.session?.access_token||''}catch{return''}}
function b64(s){const p='='.repeat((4-s.length%4)%4),r=atob((s+p).replace(/-/g,'+').replace(/_/g,'/')),a=new Uint8Array(r.length);for(let i=0;i<r.length;i++)a[i]=r.charCodeAt(i);return a}
async function enablePush(){const t=token();if(!t||!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))return false;try{const reg=await navigator.serviceWorker.register('/dexters-sw.js');await navigator.serviceWorker.ready;if(Notification.permission==='default')await Notification.requestPermission();if(Notification.permission!=='granted')return false;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(V)});const r=await fetch(U+'/functions/v1/customer-web-push',{method:'POST',headers:{apikey:K,Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify({action:'subscribe',subscription:sub.toJSON()})});return r.ok}catch(e){console.warn('Dexters push setup failed',e);return false}}
window.dextersEnablePush=enablePush;
function shell(){if(document.getElementById('dextersInboxBtn'))return;const b=document.createElement('button');b.id='dextersInboxBtn';b.type='button';b.setAttribute('aria-label','Notifications');b.innerHTML='🔔<span id="dextersInboxBadge"></span>';b.style.cssText='position:fixed;right:14px;top:14px;z-index:99970;width:48px;height:48px;border:1px solid #ffffff2b;border-radius:50%;background:#132038;color:#fff;font-size:21px;box-shadow:0 8px 24px #0005';document.body.appendChild(b);const p=document.createElement('div');p.id='dextersInboxPanel';p.style.cssText='display:none;position:fixed;inset:0;z-index:99990;background:#08101dee;color:#fff;padding:18px;overflow:auto;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif';p.innerHTML='<div style="max-width:520px;margin:auto"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px"><h2 style="margin:0">Notifications</h2><button id="dextersInboxClose" class="btn" type="button">Close</button></div><p style="color:#c4cfdf">Order updates and messages from Dexter’s.</p><div id="dextersInboxList"></div></div>';document.body.appendChild(p);b.onclick=()=>{p.style.display='block';load(true)};document.getElementById('dextersInboxClose').onclick=()=>p.style.display='none'}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function load(mark){const t=token();if(!t)return;try{const r=await fetch(U+'/rest/v1/customer_notification_inbox?select=id,title,body,created_at,read_at,data&order=created_at.desc&limit=50',{headers:{apikey:K,Authorization:'Bearer '+t,Accept:'application/json'},cache:'no-store'});if(!r.ok)return;const rows=await r.json();const unread=rows.filter(x=>!x.read_at);const badge=document.getElementById('dextersInboxBadge');if(badge){badge.textContent=unread.length?String(Math.min(unread.length,99)):'';badge.style.cssText=unread.length?'position:absolute;right:-2px;top:-2px;min-width:19px;height:19px;padding:0 4px;border-radius:10px;background:#ff394d;color:#fff;font:800 11px/19px system-ui;text-align:center':'display:none'}const list=document.getElementById('dextersInboxList');if(list){list.innerHTML=rows.length?rows.map(x=>'<div style="padding:14px;margin:10px 0;border-radius:14px;border:1px solid #ffffff1c;background:'+(x.read_at?'#ffffff08':'#ffffff12')+'"><div style="font-weight:900">'+esc(x.title)+'</div><div style="margin-top:5px;color:#d8e1ee;line-height:1.45">'+esc(x.body)+'</div><div style="margin-top:7px;font-size:12px;color:#91a0b4">'+new Date(x.created_at).toLocaleString()+'</div></div>').join(''):'<div style="padding:20px;text-align:center;color:#aab7c8">No notifications yet.</div>'}if(mark&&unread.length){await fetch(U+'/rest/v1/customer_notification_inbox?id=in.('+unread.map(x=>x.id).join(',')+')',{method:'PATCH',headers:{apikey:K,Authorization:'Bearer '+t,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({read_at:new Date().toISOString()})});setTimeout(()=>load(false),300)}}catch{}}
shell();setTimeout(()=>{shell();load(false);if(Notification.permission==='granted')enablePush()},1200);setInterval(()=>load(false),30000);window.addEventListener('focus',()=>load(false));})();